### ISSUE TITLE
Unstackable Mesh

### ISSUE THREAD

**Issue by RoyalReject** [BloodWorkXGaming/ExNihiloCreatio#100]
The mesh's do not stack causing huge problems with storing and also changing out sieves. Allow stacking like in older versions of ExNihilo

**Comment by BloodWorkXGaming** [comment]
Okey, so, I know, this issue was opened a long time ago, but the problem with this is that the meshes are enachantable, and it might cause problems if you put a whole stack in the enchantment table at once.

**Comment by RoyalReject** [comment]
I see, but in the one before they were also enchantable and stacked but im not 100%. If there is anything i can help with just say the word.

**Comment by SirLyle** [comment]
So I compiled a version with max stack set to 64 in ItemMesh.java:

* Vanilla Enchanting Tables don't take stacked items in the item slot
* Anvils show the bug where you can enchant an entire stack with a single book.

Ways around this bug:

    @Override
    public boolean isBookEnchantable(ItemStack stack, ItemStack book) {
        return stack.getCount() == 1;
    }

I will make a pull req with this fix and a configurable stacksize (default 16).

**Comment by BloodWorkXGaming** [comment]
Added by #112
