### ISSUE TITLE
Sieve Registry load strange

### ISSUE THREAD

**Issue by Rams59** [BloodWorkXGaming/ExNihiloCreatio#101]
Everytime i start a custom modpack. I get a different supply on sieveable things. Sometimes all THe things that schould e available are there sometime just dust is sievable and so on. I changed the config a bit. but im sure that i did it correct. Just strange that its sometimes correct and sometimes not

**Comment by SirLyle** [comment]
What things are inconsistent when registering? If its just the ores it's possible load order is affecting it. Ex Nihilo attempts to use the ore dict  to know if things like copper exist and that it should add the pieces/chunks.

Could you put your configs and a list of mods which give different sieve lists in a pastebin?

**Comment by Rams59** [comment]
I will load up the configs later on.
whats inconsicstent is the thongs sievable e.g. Sand, Gravel, Dust or dirt. Sometimes i can sieve verything sometimes just sand and gravel, sometimes just dust.

**Comment by BloodWorkXGaming** [comment]
Are you sure you are not confusing the different mesh types? On some you
can only sieve specific stuff

Rams59 <notifications@github.com> schrieb am Do., 2. Aug. 2018, 17:18:

**Comment by Rams59** [comment]
yeah im very sure. I have autosieves running with 2 differents meshes. THey run perfecty first, when i reload the pack suddendly they dont wokr because gravel doesn't even show up as sievable at all. Its about whats sievable not what i get out of the sieves

https://pastebin.de/71/
here the registry of the sieves. I took the leaves out not much more just added Chorus

**Comment by BloodWorkXGaming** [comment]
Okey, so check your json with this tool for errors: https://jsonlint.com/
The one you posted has one and that is most likely the reason why it isn't loading correctly when you reload the game.
