### ISSUE TITLE
uranium isnt registered as an ore on a fresh profile.

### ISSUE THREAD

**Issue by majijn** [BloodWorkXGaming/ExNihiloCreatio#102]
I recall uranium being added automatically to the ore registry and the sieve registry, is this not the case anymore? or am I just misremembering?
![2018-08-01_17 37 36](https://user-images.githubusercontent.com/18368034/43532538-a698add6-95b2-11e8-8d62-ddd3dfddbdd0.png)

**Comment by SirLyle** [comment]
It might've on an previous mod, Creatio is not set up to do that. It does yellorium with a uranium oredict if big reactors is installed.

If you have a color suggestion I could add uranium to [the defaults](https://github.com/BloodWorkXGaming/ExNihiloCreatio/blob/1.12/src/main/java/exnihilocreatio/recipes/defaults/ExNihilo.java#L266) or add an IE/IC2 [compat class](https://github.com/BloodWorkXGaming/ExNihiloCreatio/tree/1.12/src/main/java/exnihilocreatio/recipes/defaults).

**Comment by majijn** [comment]
I had added the colour as 4e5b43 ;
it seems close ish enough to Immersive engineering's

but then I messed up the fluidblock transform registry and the sieve registry and disabled it again because I didnt feel like troubleshooting my jsons I just wanted to plug and play (though that's just delaying the inevitable because I will have to add stuff because I want to add ways of getting astral sorcery to my skyblock)

if you take the time to add it to the defaults I would be very thankful!

**Comment by majijn** [comment]
the chunk drops for uranium should probably be rarer or as rare as the gem drops I reckon
