### ISSUE TITLE
Crash after using arcane ensorcellator

### ISSUE THREAD

**Issue by RandomLibrarian** [BloodWorkXGaming/ExNihiloCreatio#103]
Hi there, in StoneBlock modpack and using arcane ensorcellator I've crashed as soon as the process completes right before it output the enchanted book. kinglemming relays this is an Ex Nihilio issue. Could you have a look?

https://pastebin.com/vt9cSNLL

**Comment by SirLyle** [comment]
Going to need some more info. What were you trying to do with an arcane ensorcellator and a barrel (I think?)
