### ISSUE TITLE
filling a water bottle with water from a barrel doesnt work if your hotbar is full.

### ISSUE THREAD

**Issue by majijn** [BloodWorkXGaming/ExNihiloCreatio#105]
you need at least one free hotbar slot for it to give you water, otherwise the bottle will only move into your inventory, but empty, even if you only have are only holding one bottle

**Comment by SirLyle** [comment]
I can't reproduce this error. What other mods do you have installed?

**Comment by majijn** [comment]
![lightskyblock mods](https://user-images.githubusercontent.com/18368034/43970019-5992a7dc-9ccc-11e8-9c8c-5a86dc37a40e.png)

**Comment by SirLyle** [comment]
I was never able to reproduce this error. Do you still have it?

**Comment by majijn** [comment]
can't seem to reproduce this any longer! (however I didnt check with the exact same mods because I dont have that pack anymore )
