### ISSUE TITLE
[suggestion] bump up iron drops compared to other ores on default settings

### ISSUE THREAD

**Issue by majijn** [BloodWorkXGaming/ExNihiloCreatio#107]
other mods are rather iron hungry, including mods which add the other metals, still tend to use iron more than the other resources
perhaps make iron scale faster than other resources when upgrading meshes and have a higher cap when     you get to diamond mesh level? and/or nerf the other metal resource drops a touch

also gold which is used less, drops equally often in the blocks iron drops from, and gold also has netherrack which only drops gold
perhaps red sand could/should  have iron drops added to it?
and to play into that, perhaps a mesh shouldnt drop seeds and only drop pebbles ? I'd say flint , might be the best candidate for that

**Comment by SirLyle** [comment]
Pull #106 also has parts of this suggestion.

**Comment by BloodWorkXGaming** [comment]
Closed by #106, Thanks to @SirLyle
