### ISSUE TITLE
[Suggestion] Cross mod support for "Inspirations" crooks

### ISSUE THREAD

**Issue by SirLyle** [BloodWorkXGaming/ExNihiloCreatio#110]
Add support for inspirations crooks (and possibly suppress the crafting of ex nihilo crooks since Inspirations' have more features).

**Comment by SirLyle** [comment]
Added to PR #113.

**Comment by SirLyle** [comment]
@blay09 This Inspirations compat may result in there being no recipe for compressed crooks (if Ex Nihilo crooks are disabled). Ex Compressum may need to include an alternate recipe using Inspirations' crooks.

**Comment by BloodWorkXGaming** [comment]
Added by PR, so closing, thanks SirLyle ^^
