### ISSUE TITLE
sifting leaf blocks with an enchanted mesh gives fish?

### ISSUE THREAD

**Issue by majijn** [BloodWorkXGaming/ExNihiloCreatio#111]
![2018-08-17_05 34 33](https://user-images.githubusercontent.com/18368034/44267505-c7423380-a22e-11e8-93e7-cd418a38f0ed.png)
![2018-08-17_05 39 19](https://user-images.githubusercontent.com/18368034/44267533-e214a800-a22e-11e8-88c5-0c82a56dbd00.png)

**Comment by SirLyle** [comment]
Sieve luck of the sea enchantment makes sieves drop fish.

**Comment by SirLyle** [comment]
I'm closing this since there doesn't seem to be an issue (just a question). Reopen/submit a new one if there is an issue.

**Comment by majijn** [comment]
and here I was thinking it would make rarer items drop more often instead...

**Comment by SirLyle** [comment]
Sieve fortune does that.
