### ISSUE TITLE
[Suggestion] Forestry Support

### ISSUE THREAD

**Issue by TheLimePixel** [BloodWorkXGaming/ExNihiloCreatio#114]
The original Ex Nihilo had Artificial Hives which when in a Barrel with Seed Oil get turned into Scented ones and then, when placed in certain biomes and under certain condition, eventually turned into the various Hives. Could this feature or something similar to it be added?

**Comment by BloodWorkXGaming** [comment]
The current PR I merged earlier added some support for bees from sifting,
is that enough or do you need the actual hives?

EmosewaPixel <notifications@github.com> schrieb am Do., 13. Sep. 2018,
22:26:

**Comment by TheLimePixel** [comment]
I would prefer having the Hive system as it's quite a unique thing and makes more sense than sifting something for bees. It also works better than the Bee Attractors mods have as you know what you're going to get.

**Comment by SirLyle** [comment]
I think the biggest blocker to implementing the artificial hive would be textures.
