### ISSUE TITLE
Empty NBT Data on Sieve Products

### ISSUE THREAD

**Issue by NielsPilgaard** [BloodWorkXGaming/ExNihiloCreatio#115]
Hey o/

Any item obtained through sieving has empty NBT data, instead of no NBT data.

exnihilocreatio-1.12-0.3.1

**Comment by BloodWorkXGaming** [comment]
Are you sure you are on 0.3.1? Not 3.0? Because the 3.1 update should have
fixed that... ^^

Niels Pilgaard Grøndahl <notifications@github.com> schrieb am Di., 18. Sep.
2018, 18:40:

**Comment by NielsPilgaard** [comment]
Yes, I'm absolutely sure, sorry :P

**Comment by BloodWorkXGaming** [comment]
Quick question:
Do you have json recipes enabled or disabled?

**Comment by NielsPilgaard** [comment]
Enabled.

**Comment by BloodWorkXGaming** [comment]
Okey, so, I'll gonna take a wild guess here:
You didn't have it enabled prior, enabled it on 3.0, then updated it to 3.1
but kept the same json files?

Niels Pilgaard Grøndahl <notifications@github.com> schrieb am Di., 18. Sep.
2018, 22:00:

**Comment by NielsPilgaard** [comment]
Nope, incorrect :p I skipped 3.0, and json loading has been enabled for months.

It's in the modpack Enigmatica 2: Expert Skyblock, if that makes any difference.

**Comment by BloodWorkXGaming** [comment]
Okey, so, before I release a non fixed jar again could please try this jar:
[exnihilocreatio-1.12-0.3.1-test1.zip](https://github.com/BloodWorkXGaming/ExNihiloCreatio/files/2396660/exnihilocreatio-1.12-0.3.1-test1.zip)

**Comment by NielsPilgaard** [comment]
Absolutely, give me a few minutes :)

**Comment by NielsPilgaard** [comment]
Scratch that, I'll test it this evening.

**Comment by NielsPilgaard** [comment]
Yes that fixes it, thank you!

**Comment by BloodWorkXGaming** [comment]
Awesome, thanks for testing, will release hotfix take 2 then soon ^^

**Comment by BloodWorkXGaming** [comment]
New version was just uploaded to curse, so should be ready to be used in like few hours ^^
