### ISSUE TITLE
Crooks and veinminer?

### ISSUE THREAD

**Issue by DrasticGray** [BloodWorkXGaming/ExNihiloCreatio#116]
In the old ex nihilo veinminer would automatically configure crooks when they were detected. Is there some way for creatio to tell veinminer that these are the same thing with a different ID? If so could you add it into the mod, and if not, do you think there's a workaround?

**Comment by SirLyle** [comment]
I'm afraid I don't understand the request. This version uses an event listener and checks what item the player is holding when a block is broken, so it should work if Veinminer calls a normal block breaking event. I know it works out of the box with OreExcavation.

If it is not working in Veinminer I suggest using OreExcavation instead.

**Comment by SirLyle** [comment]
It appears that Veinminer has a [VeinminerModSupport Mod](https://github.com/portablejim/VeinMiner/tree/1.12/src/main/java/portablejim/veinminermodsupport) which needs to be updated for support. If you want to use VeinMiner instead of OreExcavation open an issue on their github.
