### ISSUE TITLE
barrel lighting causes lag on low end systems

### ISSUE THREAD

**Issue by Topside08** [BloodWorkXGaming/ExNihiloCreatio#118]
this isn't that surprising to me I don't expect you to fix Minecraft's lighting but an option to disable barrels emitting light would be useful the lighting updates that happen when I make netherrack/endstone tank my framerate

Also what does this line in the config do
B:enableBarrelTransformLighting=true

**Comment by SirLyle** [comment]
That flag tells the barrel to update its lighting when transforming contents to/from a lit state.

I can add a flag to just turn the entire lighting thing off. It'll have to be the same setting on the server unfortunately.
