### ISSUE TITLE
Crash on load 1.12-0.1.2

### ISSUE THREAD

**Issue by Nodachi216** [BloodWorkXGaming/ExNihiloCreatio#12]
Crash on load with 1.12-0.1.2
https://pastebin.com/1rFqC5Ge

**Comment by Fundryi** [comment]
Was going to report the same hope this can be fixed fast :P

**Comment by BloodWorkXGaming** [comment]
Strange... No idea that can possibly can happen... Will fix tomorrow

**Comment by BloodWorkXGaming** [comment]
fixed in the new build
