### ISSUE TITLE
Dupe bug with /dank/null integration and sieve

### ISSUE THREAD

**Issue by valarnin** [BloodWorkXGaming/ExNihiloCreatio#121]
Apologies if this is already fixed in latest version.

Version: 1.12-0.2.4
/dank/null Version: 1.12-1.4.33

Playing on the latest Stoneblock pack, version 1.0.17.

The last item in the slot in the dank null is never consumed, allowing you to sieve it infinitely.

![screenshot from 2018-09-30 11-30-28](https://user-images.githubusercontent.com/6119598/46259229-99dedb80-c4a4-11e8-99af-6114745a8b5d.png)

![screenshot from 2018-09-30 11-30-35](https://user-images.githubusercontent.com/6119598/46259228-99dedb80-c4a4-11e8-8539-ed0749609f74.png)

![screenshot from 2018-09-30 11-30-45](https://user-images.githubusercontent.com/6119598/46259227-99dedb80-c4a4-11e8-998a-cdd8888e5e2d.png)

![screenshot from 2018-09-30 11-30-54](https://user-images.githubusercontent.com/6119598/46259226-99464500-c4a4-11e8-848d-6842713271af.png)

![screenshot from 2018-09-30 11-31-19](https://user-images.githubusercontent.com/6119598/46259225-99464500-c4a4-11e8-8721-4b76d2481391.png)

**Comment by SirLyle** [comment]
Can confirm it still exists in the latest 1.12 branch.

* Seems it has to be 1 block exactly
* Any of the modes other than "extract all".

**Comment by BloodWorkXGaming** [comment]
@p455w0rd Any idea on which side this bug is?
Haven't investigated it yet, but maybe you already know it?

**Comment by p455w0rd** [comment]
ok, so the way the inventory (that ex nihilo sees) works, is it only shows what's usable...I'll have to look into this when I get time, this shouldn't be happening unless you're accessing the inventory via methods other than the IItemHandler..likely on my side

**Comment by NielsPilgaard** [comment]
Did you have a chance to look into this issue @p455w0rd? :)
