### ISSUE TITLE
Insane Network Usage

### ISSUE THREAD

**Issue by phit** [BloodWorkXGaming/ExNihiloCreatio#123]
Seems like the crucibles use a huge amount of bandwith when constantly being filled and emptied through automation.

four of them are pushing a whopping 730 kilobyte/s to a single player, leading to very high latency for the receiving player or disconnects if their connection can't handle it

exnihilocreatio-1.12-0.2.4.jar (Modpack is in Stoneblock 1.0.7)

## setup
![2018-10-05_13 31 22](https://user-images.githubusercontent.com/2097483/46532894-fd9d4600-c8a2-11e8-8a48-6fff67c71569.png)

Profiling of network usage via [TickProfiler](https://github.com/MinimallyCorrect/TickProfiler)

## with
![2018-10-05_13 33 35](https://user-images.githubusercontent.com/2097483/46532975-45bc6880-c8a3-11e8-90dc-6537a816b1e4.png)

## without
![2018-10-05_13 34 43](https://user-images.githubusercontent.com/2097483/46533009-700e2600-c8a3-11e8-8107-384f31b20ac5.png)

**Comment by BloodWorkXGaming** [comment]
Ooookey, let's say I knew it was quite bad and used waaay more than it
should but that is way worse than I was expecting...
Will try to solve it when I have the time...

phit <notifications@github.com> schrieb am Fr., 5. Okt. 2018, 13:37:

**Comment by phit** [comment]
patched it serverside for us https://gist.github.com/phit/c9f086fb8bc5dddf4a8279d1a6df72d8

![2018-10-05_15 08 22](https://user-images.githubusercontent.com/2097483/46537028-8b336280-c8b0-11e8-9ba4-67c27086bfa8.png)
