### ISSUE TITLE
Sieve and Forestry Saplings 

### ISSUE THREAD

**Issue by Sunekaer** [BloodWorkXGaming/ExNihiloCreatio#125]
Hey

So im trying to add forestry sapling to the SieveRegistry but cant get it to work, could you assist me?

This is the sapling i would like to add
`<forestry:sapling>.withTag({IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "forestry.treeOak", UID0: "forestry.treeOak", Slot: 0 as byte}, {UID1: "forestry.heightSmall", UID0: "forestry.heightSmall", Slot: 1 as byte}, {UID1: "forestry.saplingsAverage", UID0: "forestry.saplingsAverage", Slot: 2 as byte}, {UID1: "forestry.fruitApple", UID0: "forestry.fruitApple", Slot: 3 as byte}, {UID1: "forestry.yieldLowest", UID0: "forestry.yieldLowest", Slot: 4 as byte}, {UID1: "forestry.sappinessLowest", UID0: "forestry.sappinessLowest", Slot: 5 as byte}, {UID1: "forestry.leavesNone", UID0: "forestry.leavesNone", Slot: 6 as byte}, {UID1: "forestry.maturationFaster", UID0: "forestry.maturationFaster", Slot: 7 as byte}, {UID1: "forestry.i1d", UID0: "forestry.i1d", Slot: 8 as byte}, {UID1: "forestry.fireproofFalse", UID0: "forestry.fireproofFalse", Slot: 9 as byte}]}})`

but when i take that data with in withTag(), and paste it in to "nbt":  it crashes my SieveRegistry..

`
"forestry:humus": [
		{
			"drop": {
				"name": "forestry:sapling",
				"meta": 0,
				"nbt": {
					IsAnalyzed: 0 as byte,
					Genome: {
						Chromosomes: [{
							UID1: "forestry.treeOak",
							UID0: "forestry.treeOak",
							Slot: 0 as byte
						}, {
							UID1: "forestry.heightSmall",
							UID0: "forestry.heightSmall",
							Slot: 1 as byte
						}, {
							UID1: "forestry.saplingsAverage",
							UID0: "forestry.saplingsAverage",
							Slot: 2 as byte
						}, {
							UID1: "forestry.fruitApple",
							UID0: "forestry.fruitApple",
							Slot: 3 as byte
						}, {
							UID1: "forestry.yieldLowest",
							UID0: "forestry.yieldLowest",
							Slot: 4 as byte
						}, {
							UID1: "forestry.sappinessLowest",
							UID0: "forestry.sappinessLowest",
							Slot: 5 as byte
						}, {
							UID1: "forestry.leavesNone",
							UID0: "forestry.leavesNone",
							Slot: 6 as byte
						}, {
							UID1: "forestry.maturationFaster",
							UID0: "forestry.maturationFaster",
							Slot: 7 as byte
						}, {
							UID1: "forestry.i1d",
							UID0: "forestry.i1d",
							Slot: 8 as byte
						}, {
							UID1: "forestry.fireproofFalse",
							UID0: "forestry.fireproofFalse",
							Slot: 9 as byte
						}]
					}
				}
			},
			"chance": 0.08,
			"meshLevel": 1
		}
	]
`

**Comment by SirLyle** [comment]
Please upload your Jason file and crash log to pastebin.

**Comment by Sunekaer** [comment]
Its not crashing the game, its when i add this part, none of the stuff from my SieveRegistry.json gets loaded
`"forestry:humus": [ { "drop": { "name": "forestry:sapling", "meta": 0, "nbt": { IsAnalyzed: 0 as byte, Genome: { Chromosomes: [{ UID1: "forestry.treeOak", UID0: "forestry.treeOak", Slot: 0 as byte }, { UID1: "forestry.heightSmall", UID0: "forestry.heightSmall", Slot: 1 as byte }, { UID1: "forestry.saplingsAverage", UID0: "forestry.saplingsAverage", Slot: 2 as byte }, { UID1: "forestry.fruitApple", UID0: "forestry.fruitApple", Slot: 3 as byte }, { UID1: "forestry.yieldLowest", UID0: "forestry.yieldLowest", Slot: 4 as byte }, { UID1: "forestry.sappinessLowest", UID0: "forestry.sappinessLowest", Slot: 5 as byte }, { UID1: "forestry.leavesNone", UID0: "forestry.leavesNone", Slot: 6 as byte }, { UID1: "forestry.maturationFaster", UID0: "forestry.maturationFaster", Slot: 7 as byte }, { UID1: "forestry.i1d", UID0: "forestry.i1d", Slot: 8 as byte }, { UID1: "forestry.fireproofFalse", UID0: "forestry.fireproofFalse", Slot: 9 as byte }] } } }, "chance": 0.08, "meshLevel": 1 } ]`

and  the ex nihilo log only says

[15:42:38] [INFO] ModConfig Loaded: true
[15:42:38] [INFO] JEI: Compost Recipe Pages Loaded:         2
[15:42:38] [INFO] JEI: Fluid Block Transform Recipes Loaded:       23
[15:42:38] [INFO] JEI: Fluid On Top Recipes Loaded:       2
[15:42:38] [INFO] JEI: Fluid Transform Recipes Loaded:    2
[15:42:38] [INFO] JEI: Hammer Recipes Loaded:             32
[15:42:38] [INFO] JEI: Heat Sources Loaded:             11
[15:42:38] [INFO] JEI: Sieve Recipes Loaded:              0
[15:42:38] [INFO] JEI: Stone Crucible Recipes Loaded:       1

[SieveRegistry.zip](https://github.com/BloodyMods/ExNihiloCreatio/files/2461572/SieveRegistry.zip)

**Comment by BloodWorkXGaming** [comment]
That's because /ct hand gives a different syntax than the normal json...
I know craftgroovy has a command for it, buut that's just tedious to
install it for that.
Might need a command here or in crt.

Sunekaer <notifications@github.com> schrieb am Di., 9. Okt. 2018, 19:41:

**Comment by Sunekaer** [comment]
Okay ill try with craftgroovy ty

**Comment by BloodWorkXGaming** [comment]
Don't fully remember the command, was something along the lines of /cg nbt
or something....

Sunekaer <notifications@github.com> schrieb am Di., 9. Okt. 2018, 20:04:

**Comment by Sunekaer** [comment]
/cg hand
that works thank you guys

**Comment by Sunekaer** [comment]
Hey so new problem

i added 35 forestry saplings, but when i load up the game it only shows it as one recipe

![fsapling](https://user-images.githubusercontent.com/18720460/46693169-5bb28c00-cc09-11e8-8ef3-c7f1f986c195.PNG)

[SieveRegistry.zip](https://github.com/BloodyMods/ExNihiloCreatio/files/2461845/SieveRegistry.zip)

log:
[21:18:01] [INFO] ModConfig Loaded: true
[21:18:01] [INFO] JEI: Compost Recipe Pages Loaded:         2
[21:18:01] [INFO] JEI: Fluid Block Transform Recipes Loaded:       23
[21:18:01] [INFO] JEI: Fluid On Top Recipes Loaded:       2
[21:18:01] [INFO] JEI: Fluid Transform Recipes Loaded:    2
[21:18:01] [INFO] JEI: Hammer Recipes Loaded:             32
[21:18:01] [INFO] JEI: Heat Sources Loaded:             11
[21:18:01] [INFO] JEI: Sieve Recipes Loaded:              26
[21:18:01] [INFO] JEI: Stone Crucible Recipes Loaded:       1

**Comment by BloodWorkXGaming** [comment]
Does it drop correctly tho?
So issue with jei or whole thing?

Sunekaer <notifications@github.com> schrieb am Di., 9. Okt. 2018, 21:24:

**Comment by Sunekaer** [comment]
the whole thing
it only drops the Apple Oak Sapling, but random amounts, first i got 4 then 1 then 5 then 3

**Comment by Sunekaer** [comment]
Im using forge 2768 and forestry_1.12.2-5.8.1.350 if you guys need that info, but it also happened on older versions of forge and forestry 
https://minecraft.curseforge.com/projects/stoneblock/files/2626239

**Comment by SirLyle** [comment]
There is a bug in the latest version of of the JSON parser, not sure that bug got pushes yet. Not sure if it is related. But once I patched in dev I got different saplings.

The JEI compat does have a bug (it ignores NBT when deciding if items are equal). Can you test it with this build ([mediafire link](https://www.mediafire.com/file/6dzcjv81y3o9bbj/exnihilocreatio-1.12-0.3.3.jar/file)) It should have the correct drops and JEI working.

If that works then the fix is included in my existing pull req.

**Comment by SynexWolf** [comment]
It kind of fixed it? It now shows up separately but the chances are still grouped in the tool tip.
![image](https://user-images.githubusercontent.com/25542341/48128742-1c905d00-e2d3-11e8-9bc2-fe5fb63d3887.png)

SieveRegistry.json
`{
      "drop": {
        "name": "thaumcraft:crystal_essence",
        "meta": -1,
        "nbt": {
          "Aspects": [{"amount": 1, "key": "aer"}]
        }
      },
      "chance": 0.05,
      "meshLevel": 4
    },
    {
      "drop": {
        "name": "thaumcraft:crystal_essence",
        "meta": -1,
        "nbt": {
          "Aspects": [{"amount": 1, "key": "ignis"}]
        }
      },
      "chance": 0.05,
      "meshLevel": 4
    },
    {
      "drop": {
        "name": "thaumcraft:crystal_essence",
        "meta": -1,
        "nbt": {
          "Aspects": [{"amount": 1, "key": "aqua"}]
        }
      },
      "chance": 0.05,
      "meshLevel": 4
    },
    {
      "drop": {
        "name": "thaumcraft:crystal_essence",
        "meta": -1,
        "nbt": {
          "Aspects": [{"amount": 1, "key": "terra"}]
        }
      },
      "chance": 0.05,
      "meshLevel": 4
    },
    {
      "drop": {
        "name": "thaumcraft:crystal_essence",
        "meta": -1,
        "nbt": {
          "Aspects": [{"amount": 1, "key": "perditio"}]
        }
      },
      "chance": 0.05,
      "meshLevel": 4
    },
    {
      "drop": {
        "name": "thaumcraft:crystal_essence",
        "meta": -1,
        "nbt": {
          "Aspects": [{"amount": 1, "key": "ordo"}]
        }
      },
      "chance": 0.05,
      "meshLevel": 4
    }`
Also, unsure if it's related to your side, but ExCompressum still has the issue, it's still showing up as one item, but the drops seems to be correct.

**Comment by SirLyle** [comment]
Does this issue persist in the latest version? The sieve JEI plugin was rewritten.

Ex Compressum has their own JEI plugins so it would be on their side.

Edit: nvm, the part that makes the tooltip is still using the old itemstack comparison method. That will be updated in the next version.

**Comment by SirLyle** [comment]
Merged. Adding to curse soon.
