### ISSUE TITLE
Large Ore Registry overflowing in JEI

### ISSUE THREAD

**Issue by CritFlaw** [BloodWorkXGaming/ExNihiloCreatio#126]
I'm working on a skyblock pack and I added in Pam's & AA's seeds to the dirt sieve registry. I know that might be asking for a lot, but I was picturing something like loot-bags when you'd view any given seed in JEI, where it cycles through 'pages' of the possible results, instead, I get this:
https://imgur.com/a/Bxy4Wxl

**Comment by SirLyle** [comment]
I think a similar enhancement was added to the compost JEI compat relatively recently, I'll take a look at implementing a similar change to the sieves ... and check the crooks.

**Comment by SirLyle** [comment]
![2019-02-05_20 06 25](https://user-images.githubusercontent.com/6723308/52314634-96db8680-2981-11e9-9950-a32434a2fbb1.png)

A pretty hackish attempt to split up items so that JEI will page them.

**Comment by CritFlaw** [comment]
Works for now.

**Comment by SirLyle** [comment]
A fix has been merged and uploaded to curse, Version 0.3.7.
