### ISSUE TITLE
Massive console spam with infested leaves

### ISSUE THREAD

**Issue by Jacky1356400** [BloodWorkXGaming/ExNihiloCreatio#13]
I think someone forgot to turn off some debug features... 
Using 0.1.1 of creatio and Forge 2457
![image](https://user-images.githubusercontent.com/11830494/29472769-beb66a12-8487-11e7-9b85-2770466bd6dd.png)

**Comment by BloodWorkXGaming** [comment]
Fixed in the 0.1.2 version (which somehow crashes)

**Comment by Jacky1356400** [comment]
Oh, didn't know it was fixed, but yeah, I've tried 0.1.2 and it crashes

**Comment by BloodWorkXGaming** [comment]
Ye, but I have no idea why... Probably something went wrong while building
or something...

**Comment by Jacky1356400** [comment]
Ah, fair enough
