### ISSUE TITLE
crash with jaopca 

### ISSUE THREAD

**Issue by TheNimbleNinja** [BloodWorkXGaming/ExNihiloCreatio#133]
when i turn on the json function the game crashes here is my crash log:https://gist.github.com/TheNimbleNinja/94c8bba95d3c57019b3b0fb9174ebe76

**Comment by SirLyle** [comment]
The error seems to be occurring in their code, it does not appear that creatio's code is being called in the stack trace.

It appears you are using an old version of Ex Nihilo Creatio, and a new version of JAOPCA. Version 2.2.8.94 of JAOPCA contains a commit message "Update to latest Ex Nihilo Creatio". Could you please update your Ex Nihilo Creatio version and test it. If the issue persists and is still not crashing on Ex Nihilo's code, I would recommend reporting it to JAOPCA

**Comment by SirLyle** [comment]
No response. Closing (others have had the same issue and it was fixed by upgrading).
