### ISSUE TITLE
Problems with TCon integration

### ISSUE THREAD

**Issue by Nodachi216** [BloodWorkXGaming/ExNihiloCreatio#14]
Couple of issues really. 

First, the mod isn't respecting a "false" setting for Tinkers compatibility in the config.

Second, the code is making the assumption that the user has left TCon at the default setting of 2 ingots from 1 ore  _and_ that the user wants an ore chunk to equate to an ore block. Personally, I prefer that a chunk equate to an ore:dust and set that up in Craft Tweaker. Perhaps we could get that option in the config?

**Comment by BloodWorkXGaming** [comment]
Added a few more config options:
https://github.com/BloodWorkXGaming/ExNihiloCreatio/blob/f18987d5d055b98cedc5692f608f64e2fbdf7487/src/main/java/exnihilocreatio/config/ModConfig.java#L70-L79

Took the opportunity to rewrite the config system as well :P

**Comment by Nodachi216** [comment]
Cool! That's awesome!
