### ISSUE TITLE
Possibly missing Aluminum Ore after updating...

### ISSUE THREAD

**Issue by ate0ate** [BloodWorkXGaming/ExNihiloCreatio#145]
After updating my personal 1.12.2 pack's version of Ex Nihilo Creatio from 0.3.2 to 0.3.3 and loading my existing world, I received the standard forge warning for missing blocks stating that Ex Nihilo Creatio Aluminum Ore is no longer present. I have not tweaked any config settings or anything like that nor do I have any special instances of Aluminum ore set to spawn. I do use several mods that add their own Aluminum ore however. Has there been changes to aluminum ore that would explain it being missing after updating?

**Comment by SirLyle** [comment]
Changes were made to prevent the creation of both aluminum and alumin*i*um. One of them should still be registered.

**Comment by ate0ate** [comment]
Ah okay, that makes sense then. I do see Aluminium is indeed registered. Thank you for the response.
