### ISSUE TITLE
Server crash (with Tinkers)

### ISSUE THREAD

**Issue by TheSnowyChickens** [BloodWorkXGaming/ExNihiloCreatio#146]
Hi,

I opened a issue at tinker's Github, because with only Tic + Mantle and Ex Nihilo (version from today) + Forgelin -> a Server can't start = server crash.

The crash -> https://pastebin.com/9F6zb2M1
Tinker's Page -> https://github.com/SlimeKnights/TinkersConstruct/issues/3746

Versions:
- Minecraft: 1.12.2
- Forge: 2808 and 2810
- Mantle-1.12-1.3.3.39
- TConstruct-1.12.2-2.12.0.115
- Foregelin: Forgelin-1.8.2
- ExNihilo: exnihilocreatio-1.12-0.3.3

Edit: KnightMiner answered, that this issue is on your side.

(Ps: I don't know, whether this crash comes from you or Tinker's, thats why I open 1 issue at your page and Tinker's page.^^)

**Comment by SirLyle** [comment]
Fixed I think and uploaded a new version to curse. Thank you for reporting.

**Comment by TheSnowyChickens** [comment]
Ty

**Comment by TheSnowyChickens** [comment]
@SirLyle 
https://pastebin.com/za5RZ3rX

1 new error. (something with AE2)

**Comment by SirLyle** [comment]
See Issue #148 for this new crash.

**Comment by TheSnowyChickens** [comment]
Ah okay, Ty²
