### ISSUE TITLE
Crash at startup after updating from 0.3.3 to 0.3.4

### ISSUE THREAD

**Issue by ate0ate** [BloodWorkXGaming/ExNihiloCreatio#148]
Using forge 2810 I get this crash at startup after attempting to update from v0.3.3 to v0.3.4...

https://pastebin.com/4PiJaQ1d

Both v0.3.2 and v0.3.3 worked fine for me in my single player world prior to this update.
Thank you for your time.

**Comment by Leo40Git** [comment]
Looking at the code... Apparently the field `net.minecraft.block.SoundType.GROUND` was removed at some point?

Crash report: https://paste.dimdev.org/ugofiqoqis.mccrash (though it's pretty much the same thing as ate's log)

**Comment by SirLyle** [comment]
Strange that updating caused this bug, the update didn't touch that code. Will investigate.

**Comment by ghost** [comment]
Thanks @SirLyle

**Comment by SirLyle** [comment]
I am unable to reproduce the crash with Ex Nihilo + Forgelin + AE2 + Tcon (to prevent issue #150).

Makes me think it is a conflict. Did you upgrade any other mods (you have a ton) recently?

**Comment by ate0ate** [comment]
I did not upgrade any further mods in my case and downgrading to v0.3.3 is my current workaround. Everything works fine using that version but as soon as I try to update to v0.3.4, I get a crash at startup. Could it be the config? Perhaps deleting it and trying fresh? I will test anything you recommend.

The only things I can think of that effect sound in any way that I use are sound filters and dynamic surroundings, but again they have been the same version for quite a while now so I don't know.

**Comment by SirLyle** [comment]
Does it crash if you start an instance with just Ex Nihilo (0.3.5) + Forgelin + Applied Energistics?

Could you provide me you config file for DynamicSurroundings? What mod are the sound filters from?

**Comment by SirLyle** [comment]
If any of you are using a published modpack + updated ex nihilo having its name would let me download all the mods in one shot.

**Comment by ate0ate** [comment]
Sound Filters is actually the name of the mod. It just adds reverb to caves and large rooms and such. Link here... https://minecraft.curseforge.com/projects/sound-filters/files/2445236

I believe have Dynamic Surroundings default config options but here is a link to my specific config file...
http://www.mediafire.com/folder/m259b5308q9mv/dsurround

Sorry I cannot provide you with a link to a specific pack but mine is not too disimilar to AllTheMods 3. Closest one I can see. Thank you for looking into this. I know it can be quite a headache.

EDIT: Whoops, sorrry, original sound filters link was wrong. Fixed now:)

**Comment by ate0ate** [comment]
Okay, hopefully big news, I do indeed crash with the same crash using JUST Ex Nihilo, Forgelin, and AE2.
Crash report here... https://pastebin.com/HD0vUBGi

**Comment by ate0ate** [comment]
Okay, more info. I actually crash using ONLY EX Nihilo Creaatio and Forgelin. No AE2 or anything at all. The crash is for a missing WATER rather than GROUND though... https://pastebin.com/9bvesfEn

**Comment by SirLyle** [comment]
That is "good" news. Thank you.

Can you provide me your <minecraft>/logs/debug.log file.

**Comment by SirLyle** [comment]
I think it may be due to having built the mod with a fairly old version of Forge. Could you try this version and tell me if it fixes your error:

https://www.mediafire.com/file/wr7n2a1fne2n2mw/exnihilocreatio-1.12-0.3.5.1.jar/file

**Comment by ate0ate** [comment]
Sure thing...
I don't see anything mentioning debug at all, but there are two files in my logs folder. Contents here... http://www.mediafire.com/folder/icei3e1zz6bn4/logs

**Comment by ate0ate** [comment]
You did it! That test version does fix my issue. I tried it in a test using just AE2, Forgelin, and ENC as well as in my ridiculous mod pack. All is working as intended in both instances it seems. You have my blessing to close the issue. I was hesitant to do so myself since others were involved. Thank you so much!

**Comment by rcsob657** [comment]
Hello, if this 3.5.1 fixes the error (mine says ground block) can you please upload it to TWITCH

**Comment by ate0ate** [comment]
While it does indeed fix the error for me I imagine that the upload to Curse is waiting for a few more tests to also confirm things are working as intended. I'm sure once everything is confirmed working properly the fix will then be uploaded:)

**Comment by CritFlaw** [comment]
0.3.5.1 works on Forge 2796!

**Comment by SirLyle** [comment]
So it fixes your crash too? Alright I will move the curse release from alpha to beta.

**Comment by CritFlaw** [comment]
Yep

**Comment by SirLyle** [comment]
Fix released to curse.

**Comment by TheSnowyChickens** [comment]
Server and Client are fixed, ty.
