### ISSUE TITLE
Crash still happening in 0.3.5

### ISSUE THREAD

**Issue by CritFlaw** [BloodWorkXGaming/ExNihiloCreatio#152]
It's a different crash log, but one nonetheless - https://pastebin.com/aMZrqPrx

**Comment by SirLyle** [comment]
This appears to be different from the crashes everyone else has had today. Can you use the version I attached to this Issue (https://github.com/BloodyMods/ExNihiloCreatio/issues/148#issuecomment-460012790) and tell me if it fixes your crash?
