### ISSUE TITLE
[0.3.5] No Such Field Error

### ISSUE THREAD

**Issue by kreezxil** [BloodWorkXGaming/ExNihiloCreatio#153]
Possibly related to #152 and #148 

Issue:  0.3.5 crashes dedicated server Forge 1.12.2 build 2810

Notes:
     on startup while looking for missing field, possibly a client side field

crash report:
http://paste.ubuntu.com/p/5kT8ZFqDcx/

fml server latest:
http://paste.ubuntu.com/p/b3qCgGh5pZ/

**Comment by SirLyle** [comment]
Duplicate Issue #148.
