### ISSUE TITLE
No JEI for Sieves

### ISSUE THREAD

**Issue by CritFlaw** [BloodWorkXGaming/ExNihiloCreatio#155]
The latest version of Ex Nihilo, sieve recipes don't show up in JEI, instead only showing Ex Compressum's heavy sieve. Tried with and without json loading. 

Forge version 2796
Mod version 0.3.5.1

**Comment by SirLyle** [comment]
Are you attempting to look up the recipes using the sieve or the meshes? I can see them if I look them up with the sieves.

**Comment by CritFlaw** [comment]
With the sieves.

**Comment by SirLyle** [comment]
Can you please provide your log, there may be an "[Client thread/ERROR] [jei]" where the JEI plugin is failing. Try searching your logs for "exnihilocreatio.compatibility.jei.CompatJEI"

**Comment by CritFlaw** [comment]
Yes, there does seem to be an issue happening with JEI https://gist.github.com/CritFlaw/79bb9e459cadd52ff1e79e3650c079b8

**Comment by SirLyle** [comment]
Appears to actually be a problem with the ex nihilo JEI plugin.

**Comment by SirLyle** [comment]
Issue is related to Issue #150, basically even though the tinkers derived class is never called, Java is trying to validate the classes.

**Comment by CritFlaw** [comment]
Lovely

**Comment by SirLyle** [comment]
Fix pushed to curse.

**Comment by CritFlaw** [comment]
Ok, that does fix it, but now we're back to pre-2019 problems, with it doing this: 
https://imgur.com/a/0WgleBt

**Comment by SirLyle** [comment]
I don't think that was ever fixed.

**Comment by CritFlaw** [comment]
Oh, I assumed that was one of the things addressed in the initial update....

**Comment by SirLyle** [comment]
I think @Tencao had a branch where he was working on that. The big initial update was just my dev branch.

**Comment by CritFlaw** [comment]
Is it the same issue Ex Compressum is having? https://github.com/blay09/ExCompressum/issues/261

**Comment by SirLyle** [comment]
Probably. Basically the JEI plugin was never designed for a large number of possible drops. It has to basically be completely re-written. I haven't seen anything in the JEI API that is really designed for limited inputs -> massive number of outputs.

Issue #126 is still open for this topic.

**Comment by CritFlaw** [comment]
What about lootbags? They have this working.

**Comment by SirLyle** [comment]
Uses a custom license so not to keen on just ripping off their code.

**Comment by CritFlaw** [comment]
Ah, I see... well that sucks. I'll limit items to fit.
