### ISSUE TITLE
Can't get rubber tree seeds

### ISSUE THREAD

**Issue by spcmnk** [BloodWorkXGaming/ExNihiloCreatio#156]
**I can't get rubber tree seeds from sieving. I don't know what to do. I have IndustrialCraft 2 mod, but I can't obtain rubber tree seeds. Or these seeds removed from Ex Nihilo: Creatio mod, or I do something wrong?**
![321](https://user-images.githubusercontent.com/47331299/52226329-b315ef80-28bd-11e9-8a69-87f4365a00bb.png)

Minecraft version:1.12.2
Forge version:14.23.5.2807
Ex Nihilo Creatio version:0.3.5.1

Another mods:
IndustrialCraft2 2.8.109-ex 112
Advansed Solar Panels 4.3.0
Backpack 3.0.2-1.12.2
Baubles 1.12-1.5.2
CodeChicken Lib 3.2.2.353
Durability Show 5.0.0
Energy Converters 1.2.1.11
Shadowfacts' forgelin 1.8.2
JEI 4.14.4.259
Mantle 1.3.3.39
Tinkers' Construct 1.12.2-2.12.0.115
Ex Compressum 3.0.26
Extra Utilities 2
Waila 1.8.26
Iron Chest 7.0.58 build 841
NEI 2.4.2.240
Railcraft 12.0.0-beta-4
Waila Harvestability 1.1.12
Wawla 2.5.269
Totem Expansion 1.2.2-1.12.2

**Comment by SirLyle** [comment]
Ex Nihilo Creatio has only ever added seeds for the vanilla trees. You can add the saplings to the sieve results. And I guess this issue can serve as a feature request to add rubber seeds.

**Comment by SirLyle** [comment]
New version 0.3.6 on curse has rubber seeds added.
