### ISSUE TITLE
Crooking infested leaves' string drop chance

### ISSUE THREAD

**Issue by Stormalisk** [BloodWorkXGaming/ExNihiloCreatio#158]
I have been trying to make crooks not always drop 2 string when harvesting infested leaves, as my modpack does not revolve around skyblock and I don't want it to overshadow harvestcraft cotton or other string obtainment methods.  So far the only "nerf" I can give them is to make their tick time obscenely long.

` crooking {
D:stringChance=0.5
D:stringFortuneChance=0.5
 }`
Changing those two options only seems to affect drop rates when NOT crooking, as no matter the setting a crook will always force two string to drop per block.

I am unsure if this is the intentional behavior or not of those settings.

**Comment by SirLyle** [comment]
There appears to be a missing check in BlockInfestedLeaves.onBlockHarvest(...).

**Comment by SirLyle** [comment]
A fix has been merged and uploaded to curse, Version 0.3.7.
