### ISSUE TITLE
Server Crash using new beta version

### ISSUE THREAD

**Issue by ghost** [BloodWorkXGaming/ExNihiloCreatio#165]
https://gist.github.com/Modpack-Support/41f40c3cd11baa31186db79fc3077e76

**Comment by SirLyle** [comment]
Woops put the SideOnly annotation on the wrong proxy. Fix will be uploaded to curse shortly.

**Comment by SirLyle** [comment]
Version 0.3.8.1 is approved on curse.

Thank you for reporting.
