### ISSUE TITLE
(Request) Oak Crucible

### ISSUE THREAD

**Issue by FisfulOfDice** [BloodWorkXGaming/ExNihiloCreatio#17]
The lack of an oak crucible means that you can't create water if you wind up in a non-rain biome, and even then you have to wait for it rain to fill barrels naturally.

**Comment by BloodWorkXGaming** [comment]
Already added a wooden crucible, you can play with it already if you use a newer Jenkins build. 

Small problem, how should I transfer water from the crucible to the barrel? 
Any suggestions? Water bowls maybe? Or bottles?

**Comment by Nodachi216** [comment]
I think buckets are the way to go, simple and intuitive.

**Comment by BloodWorkXGaming** [comment]
Thing is, you need water to make clay to make a crucible to make lava to
make a cobble gen, not necessarily, but it makes it a lot easier.
Therefore you need to move water before you can make a bucket.

**Comment by Nodachi216** [comment]
Just make the wooden crucible count as a barrel, same as Ex Compressum's do, problem solved! ;)

**Comment by FisfulOfDice** [comment]
Bottles might work, since you can't be sure that someone has Ceramics or a clay bucket mod installed.

**Comment by BloodWorkXGaming** [comment]
Added a crucible, I kinda suspect the one from ex compressum might be better tho, but meh :P
