### ISSUE TITLE
[Suggestion] Make more drops from Sieving / Hammering visible in a single instance from JEI

### ISSUE THREAD

**Issue by Insane96** [BloodWorkXGaming/ExNihiloCreatio#170]
Here's a concept: 
![2019-02-15_16 03 52](https://user-images.githubusercontent.com/7185104/52865593-46acb300-313d-11e9-90ea-6e2031081bf6.png)

**Comment by SirLyle** [comment]
![jei_sieve_expandable](https://user-images.githubusercontent.com/6723308/53927430-e41c4800-4054-11e9-96e5-aec30b4b0d89.png)

Is this a happy compromise?

**Comment by SirLyle** [comment]
![jei_sieve_3rows](https://user-images.githubusercontent.com/6723308/53927520-26de2000-4055-11e9-984c-a215a6bc9925.png)

Is this a happy compromise?

**Comment by Insane96** [comment]
Definitely ^^

Il Gio 7 Mar 2019, 03:17 SirLyle <notifications@github.com> ha scritto:
