### ISSUE TITLE
Gray text

### ISSUE THREAD

**Issue by spcmnk** [BloodWorkXGaming/ExNihiloCreatio#172]
During the rain, Text color in the chat goes gray. When I am holding a weapon or tool, text color goes white.
![2019-02-18_13 13 14](https://user-images.githubusercontent.com/47331299/52955075-d0a68700-339c-11e9-8863-293c72a96bcc.png)
![2019-02-18_13 13 29](https://user-images.githubusercontent.com/47331299/52955117-eddb5580-339c-11e9-9167-b7b43f1ecadf.png)

**Comment by SirLyle** [comment]
Not sure what makes you think this is a bug in Ex Nihilo Creatio.

**Comment by SirLyle** [comment]
Can you reproduce this error with only Ex Nihilo Creatio installed? Otherwise I suspect it is another mod; do you have any mods which changes rendering?

What other mods do you have installed?

**Comment by spcmnk** [comment]
I tried to reproduce this error with only Ex Nihilo mod, I didn't found this error.
I found out that Durability Show mod has this error.

**Comment by SirLyle** [comment]
I suggest reporting this issue to the affected mod.
