### ISSUE TITLE
[Suggestion] Add Command to reload jsons from in-game

### ISSUE THREAD

**Issue by Insane96** [BloodWorkXGaming/ExNihiloCreatio#173]
Somthing like `/exnihilo reload`

**Comment by SirLyle** [comment]
Such a command would end up being limited, the ore registry wouldn't be reloadable (since the minecraft item registries aren't) nor would JEI be updated for the new recipes.

**Comment by SirLyle** [comment]
So there is this command in the code base [/enreloadconfig](https://github.com/BloodyMods/ExNihiloCreatio/blob/1.12/src/main/java/exnihilocreatio/command/CommandReloadConfig.java). Does that do what you want?

**Comment by Insane96** [comment]
It reloads config not jsons
EDIT: I'm actually stupid it DOES reload json but JSONs errored.
It's good then
