### ISSUE TITLE
Oozing doll crash

### ISSUE THREAD

**Issue by Cazadorsniper** [BloodWorkXGaming/ExNihiloCreatio#174]
Right click an oozing doll on a barrel full of milk: https://pastebin.com/iQEVcZwi

**Comment by SirLyle** [comment]
I have no power at my house so I can't fix, but I suspect it is because milk doesn't have a block form.

Hopefully I can fix it tomorrow.

**Comment by SirLyle** [comment]
My power came back and I took a look at this; I wasn't able to reproduce it.

Do you know which mod is adding milk in your game? You should be able to tell by turning on advanced tooltips (F3+G) and searching in JEI for milk; when you hover over the milk square (not the bucket) you should see the mod's name in the tooltip.

**Comment by Cazadorsniper** [comment]
ok I'll see

**Comment by Cazadorsniper** [comment]
Found that Erebus and NuclearCraft add milk, although Erebus's milk turned into a bucket of milk when i pulled it out of JEI.

**Comment by Cazadorsniper** [comment]
Okay found that its The Erebus causing that crash

**Comment by SirLyle** [comment]
Okay, I could reproduce the crash with Erebus's milk; my first guess appears to have been correct. A new version should be available shortly.

**Comment by SirLyle** [comment]
A fixed version should be available on curse. Thank you for reporting.
