### ISSUE TITLE
autosifter shaking the wrong sieve

### ISSUE THREAD

**Issue by bandon41** [BloodWorkXGaming/ExNihiloCreatio#177]
i'm playing project ozone 3 with ex nihilo creatio version 1.12.2-0.3.7 installed

to automate resources i've made a settup with 3 autosieves each powered by their own waterweel, one for gravel, one for sand and one for dust

each is placed next to eachother with 3 empty spaced between

and while the waterwheel powers the correct sifter, for some reason, some sifters don't shake the sieve on top of them but those on top of other sifters

and that while the one on top of the powered sifter isn't moving at all

**Comment by SirLyle** [comment]
I believe PO3 has the sieve radius set higher than default (I think a radius of 4 instead of 2); the sieves don't actually check connectivity (just range) so some of the disconnected sieves might actually be valid to move. As a temp fix try moving them further apart.

Could you post an screenshot of your setup?

**Comment by bandon41** [comment]
while waiting for the reply i had done some testing and indeed moving them 1 more block away from eachother fixes that problem, so i guess that means the problem has been solved

thanks for taking the time to read and help

**Comment by BloodWorkXGaming** [comment]
It intentionally doesn't check connectivity as that would mean having do to
a map search instead of simply iterating over a grid which might hurt
performance badly if it is done often.

bandon41 <notifications@github.com> schrieb am Mi., 27. Feb. 2019, 08:56:

**Comment by SirLyle** [comment]
I think I have it working (along with some minor changes to how it looks)

https://gfycat.com/CanineGraveGrayreefshark

**Comment by SirLyle** [comment]
Release 0.4 has fixed this.
