### ISSUE TITLE
Drop Chance . . . . .

### ISSUE THREAD

**Issue by TheSnowyChickens** [BloodWorkXGaming/ExNihiloCreatio#184]
Hi,

![grafik](https://user-images.githubusercontent.com/29357962/54161948-262dfb00-4454-11e9-9b9c-467423520a90.png)

MC: 1.12.2
Forge: 2815
ExN: 0.3.8.3

I think, we can see (or can't see ^^) the problem. :)

**Comment by SirLyle** [comment]
So it appears that AE2 is injecting NBT data on the stack creation.

You'll need to edit your JSONs to get the fix, the defaults will be fixed in the next update.

Make each entry look like this.
```
    {
      "drop": {
        "name": "appliedenergistics2:crystal_seed",
        "meta": 0,
        "nbt": "{progress:0.0f}"
      },
      "chance": 0.01,
      "meshLevel": 1
    },
```

**Comment by TheSnowyChickens** [comment]
Okay, ty.

**Comment by TheSnowyChickens** [comment]
Ty
