### ISSUE TITLE
Sieve registry not working right

### ISSUE THREAD

**Issue by Georg255** [BloodWorkXGaming/ExNihiloCreatio#188]
Whenever I load my world, the sieve registry edits I put in rarely fully load, partially load or not load at all.  I'm on latest version 0.3.9.  I don't know what to do.

Ex Nihilo Creatio log: 

[10:19:23] [INFO] ModConfig Loaded: true
[10:19:23] [INFO] JEI: Compost Recipe Pages Loaded:         2
[10:19:23] [INFO] JEI: Fluid Block Transform Recipes Loaded:       23
[10:19:23] [INFO] JEI: Fluid On Top Recipes Loaded:       2
[10:19:23] [INFO] JEI: Fluid Transform Recipes Loaded:    1
[10:19:23] [INFO] JEI: Hammer Recipes Loaded:             26
[10:19:23] [INFO] JEI: Crook Recipes Loaded:              1
[10:19:23] [INFO] JEI: Heat Sources Loaded:             61
[10:19:23] [INFO] JEI: Sieve Recipes Loaded:              24
[10:19:23] [INFO] JEI: Stone Crucible Recipes Loaded:       1
[10:19:23] [INFO] JEI: Wood Crucible Recipes Loaded:        1

Sieve Registry edits: https://hastebin.com/somobeqaco.json

Following is my mod list:

ivtoolkit
FoamFix
AnvilFix
AppleCore
Apple Pie
Applied Energistics 2
Baubles
JEI
Botania
Mantle
Twilight Forest
Tinker's Construct
Construct's Armory
Forgelin
Ex Nihilo Creatio
Mekanism (Mekanica fork)
Tesla Core Lib
Industrial Foregoing
Cucumber
Mystical Agriculture
Mystical Aggraditions
Natura
Pam's Harvestcraft
Integration Foregoing
Pewter
Plustic
Armory Expansion
Artifacts
Attribute Fix
Atum
Quark
AutoRegLib
Better Builder's Wands
Better Questing
Bird's Foods
FlameLib
Bountiful Baubles
Ced End Cake
Chameleon
Chisels and Bits
Placebo
Clck Machine
CookieCore
CTGui
CraftTweakerJEI
CyclopsCore
DumpsterDiving
EverlastingAbilities
WAILA
ExtraBotany
FairyLights
FlexTape
FPSReducer
HeartDrops
Hexlands
Iblis Headshots
Infused Ring
Instant Unify
Item Got
JEHC
JourneyMap
JRFTL
JustAFewFish
JustEnoughResources
Large Fluid Tank
LevelUp 2
Lightning Rods
Little Utilities
Magic Feather
Mana Well
Mekanism Generators (Mekanica fork)
Mekanism Tools (Mekanica fork)
MJRLegendsLib
Patchouli
Nature's Aura
Neat
NoCTRL
RecipeHandler
Ocean Floor
Open Mods
Open Blocks
Ore Stone Variants
PiTweaks
Progressive Automation
Quantum Lights
Quark Oddities
Ration Craft
Recurrent Complex
Reliquary
RF Expansion (Better Questing addon)
SelfControl
ShadowMC
Simple Scaled Mobs
Spice Of Life: Carrot Edition
Soul Shards Respawn
Special Mobs
Standard Expansion (Better Questing Addon)
Storage Drawers
Tinker's Arsenal
Tinker's JEI
Tinker Tool Leveling
Touch Of Beacon
Uncrafted
Unnatural Absorption
Wanion Lib
Waystones
Saturation Overflow
UniDict

**Comment by SirLyle** [comment]
You do have an error in your JSON (extra comma on line 244), check with [JSONLint](https://jsonlint.com/). Not sure that is causing the problem since you said the problem is intermittent. Could you fix that and tell me if the problem persists.

I will take a look / try to replicate.

**Comment by Georg255** [comment]
OK.  I'll check.

EDIT:  Eyyyy!  It worked!  Thank you kindly!

**Comment by SirLyle** [comment]
Glad it's fixed.
