### ISSUE TITLE
JEI Shows wrong amount of items to compost

### ISSUE THREAD

**Issue by Insane96** [BloodWorkXGaming/ExNihiloCreatio#189]
Seems to be a rounding problem.
E.g. Silk Worms needed are 25, but JEI shows 26
![2019-03-25_19 32 15](https://user-images.githubusercontent.com/7185104/54944908-dd3a7400-4f34-11e9-9389-7eb4b4505a7a.png)

**Comment by SirLyle** [comment]
Yay floating point numbers.

**Comment by SirLyle** [comment]
You got this issue in just in time to make it into the new release.

**Comment by Insane96** [comment]
The fastest bug sender in the West
