### ISSUE TITLE
Tinker's Compatibility Aluminum vs. Aluminium

### ISSUE THREAD

**Issue by SirLyle** [BloodWorkXGaming/ExNihiloCreatio#19]
It appears the smeltery registery fails with the British spelling of alumin*i*um.

This can be worked around by changing all the json files, but I think a more elegant way (to make the default configs work) would be to inject some special logic into registerMeltingChunks() to handle the spelling differences. [Here is a fork where I've made the change](https://github.com/SirLyle/ExNihiloCreatio/blob/1.12/src/main/java/exnihilocreatio/compatibility/tconstruct/CompatTConstruct.java).

**Comment by BloodWorkXGaming** [comment]
Good catch, Thank you ^^ 
copied it over into the main brach, didn't bother making a PR for that single file change.
Sadly I saw it too late and I already finished up the 1.3 version on curse, so next version it will be fixed ^^
