### ISSUE TITLE
Witch Water Interactions

### ISSUE THREAD

**Issue by lynaevm** [BloodWorkXGaming/ExNihiloCreatio#191]
I'm loving the new witch water interactions (cobblegen style) but would love to suggest a few tweaks.

You offer the option to define the maximum temperature that qualifies as "cold" but I would also suggest adding a minimum temperature that qualifies as "hot" since right now anything that is defined as even slightly warmer than water essentially functions as lava.  

For packs that contain a lot of fluids, it would also be nice to be able to whitelist or blacklist fluids from these interactions.

I would actually love to be able to define any 2 liquids and what block they make in reaction.

**Comment by lynaevm** [comment]
It would also be wonderful if the list of possible blocks could be weighted

**Comment by SirLyle** [comment]
I think arbitrary fluid interactions is outside the scope of this mod (there are mods which do this), but expanding the witchwater system to be a full fledged system should be feasible. Where you imagining defining something like:

```json
{
  "fluid:otherfluid": {
    "modid:name:meta": 1,
    "modid:name1:meta": 1,
    "modid:name2:meta": 2
  }
}
```
And having the third one appear 50% of the time, and the other two only 25% each?

**Comment by SirLyle** [comment]
Version 0.4.1 has been uploaded to curse and includes the registry, I feel interactions between two fluids not in Ex Nihilo is outside the scope of this mod.
