### ISSUE TITLE
World Crashing from barrels

### ISSUE THREAD

**Issue by collin0898** [BloodWorkXGaming/ExNihiloCreatio#193]
I don't exactly know whats happening here, I made a modpack to mess with, and it just keeps crashing. It says something about barrels but I'm not 100% sure. If you know any way to fix this please get back to me.
 
https://paste.dimdev.org/deledeyaco.mccrash

**Comment by SirLyle** [comment]
What were you doing with the barrel? I.e. what was in it.

**Comment by collin0898** [comment]
> What were you doing with the barrel? I.e. what was in it.

I'm not sure, I hadn't touched any of them in forever, and they just started doing that. I have a lot of mods running so I thought maybe somehow my auto crucibles was messing it up, but Idk, stone barrels seem to work fine still, but if i try placing milk in any of them to make slime, instant crash.

**Comment by SirLyle** [comment]
Do you know what mod added your milk fluid (use jei + advanced tool tips), milk has been an issue before.

**Comment by collin0898** [comment]
> Do you know what mod added your milk fluid (use jei + advanced tool tips), milk has been an issue before.

It's forestry.

**Comment by SirLyle** [comment]
I'll take a look after work. It is the barrel rendering that is crashing, likely it is failing to grab the texture properly and is getting a null.

**Comment by collin0898** [comment]
> I'll take a look after work. It is the barrel rendering that is crashing, likely it is failing to grab the texture properly and is getting a null.

I deleted it using mcedit, but I'd still like a way to make slime and stuff for pipe sealant if possible.

**Comment by SirLyle** [comment]
So loading up a world with just forestry+ex nihilo doesn't make it crash.

Is it crashing the moment you add the milk or when you attempt the slime recipe? Is the slime recipe just the milk+mushroom recipe?

Could you try to recreate the bug in a new world without optifine installed?

**Comment by collin0898** [comment]
> So loading up a world with just forestry+ex nihilo doesn't make it crash.
> Yes
> Is it crashing the moment you add the milk or when you attempt the slime recipe? Is the slime recipe just the milk+mushroom recipe?
> Second I add the milk, I have to delete the block in mcedit to even reopen my world.
> Could you try to recreate the bug in a new world without optifine installed?
Yeah I'll see.

**Comment by SirLyle** [comment]
> > So loading up a world with just forestry+ex nihilo doesn't make it crash.

> Yes

I'd meant that in the sense that I couldn't reproduce it with just those two mods.

My current two theories are:

1. optifine is doing something weird
    * In which case you will need to report it to optifine as it is a closed source mod and there is no way for me to diagnose what it might be doing.
2. some sort of three way mod interaction
    * Did you originally start your world without forestry, and then later added it, or any other mod that adds content. Fluids can be a little screwy with registration on existing worlds. If this is the case, a new world might not demonstrate the same issue.

Is this (or at least sans optifine) a published modpack? If so I'd like a name/link so I can download the entire pack to do tests for cross mod compat.

**Comment by collin0898** [comment]
I think it may be the second, that sounds like, exactly right.

> > > So loading up a world with just forestry+ex nihilo doesn't make it crash.
> 
> > Yes
> 
> I'd meant that in the sense that I couldn't reproduce it with just those two mods.
> 
> My current two theories are:
> 
> 1. optifine is doing something weird
>    
>    * In which case you will need to report it to optifine as it is a closed source mod and there is no way for me to diagnose what it might be doing.
> 2. some sort of three way mod interaction
>    
>    * Did you originally start your world without forestry, and then later added it, or any other mod that adds content. Fluids can be a little screwy with registration on existing worlds. If this is the case, a new world might not demonstrate the same issue.
> 
> Is this (or at least sans optifine) a published modpack? If so I'd like a name/link so I can download the entire pack to do tests for cross mod compat.

I think it is the added it later part, that sounds exactly right. Is there anyway I can reset the registry without losing the progress of the world in that case?

**Comment by SirLyle** [comment]
That will break a lot more in your world than just barrels (every modded item will become a random other item). I have managed to create a world that reproduces this bug and will try to fix it.

**Comment by SirLyle** [comment]
While I try to get a more elegant solution here is a build which should at least let your  world load (with a missing texture)

[Mediafire link for 0.4.1a](https://www.mediafire.com/file/6nad01r4m9e6dfb/exnihilocreatio-1.12.2-0.4.1a.jar/file) .

**Comment by SirLyle** [comment]
A fixed (hopefully) version (0.4.1) has been uploaded to CurseForge. Thank you for reporting.

If the issue persists please open a new issue.
