### ISSUE TITLE
Slimes spawned via Witchwater+mushrooms have 10 hearts instead of a half

### ISSUE THREAD

**Issue by Insane96** [BloodWorkXGaming/ExNihiloCreatio#194]

**Comment by SirLyle** [comment]
Seriously Mojang, EntitySlimes don't calculate their max health correctly?

**Comment by Insane96** [comment]
Seems like even the jump strength is like the bigger ones

**Comment by SirLyle** [comment]
Are you sure that's not just because they can spawn in an area around the barrel including off the ground?

Health fix is included in version 0.4.1 on curse.

**Comment by Insane96** [comment]
The health problem has been fixed in 0.4.1.1.
Fixing the health problem has even fixed the jump strenght.
