### ISSUE TITLE
[Question] What normalDropPercent does?

### ISSUE THREAD

**Issue by Insane96** [BloodWorkXGaming/ExNihiloCreatio#197]
This property what is used for? `I:normalDropPercent=100` in the `world` category

**Comment by SirLyle** [comment]
It is used for the default recipes, it lets them all be modified easily in the event that someone wants to play in a non-skyblock world and doesn't want to generate JSONs and edit them all by hand.

If `B:isSkyWorld` is false then most of the default sieve recieps will be multiplied by `I:normalDropPercent` / 100.

See [this code file](https://github.com/BloodyMods/ExNihiloCreatio/blob/1.12/src/main/java/exnihilocreatio/recipes/defaults/ExNihilo.java) (ctrl+f for "getDropChance") for the affected recipes.

If this answered your question please close this issue.
