### ISSUE TITLE
[Suggestion] Make barrels milk cows that are standing on top of them.

### ISSUE THREAD

**Issue by SirLyle** [BloodWorkXGaming/ExNihiloCreatio#20]
Just a minor automation improvement that could be added. Maybe expanded into something that could be configurable for pack makers.

I'm still new to modding but [I tried my hand at it](https://github.com/SirLyle/ExNihiloCreatio-MilkBarrels) (yay open source mods to practice on).

**Comment by SirLyle** [comment]
I'm actually working on making it a definable recipe for any entity so that it can be adjusted for packs.

**Comment by BloodWorkXGaming** [comment]
This is not a bad idea, not realistic, but funny ^^

However, my concern with it being the barrels doing the milking, they
always tick and have to check for animals on top of them.
The mob walk event isn't that useful as well, because they might sometimes
stand still and won't get milked.
Calling it every tick however will make lag, even if the barrel is not
intended to be used as a milking thing.

**Comment by SirLyle** [comment]
onEntityWalk seems to be working when the cow is restricted to a 1x1 area over a a barrel; which is how I imagine most people would set it up.

**Comment by SirLyle** [comment]
Well I think I have it working using the entity walking event, a configurable cool down, and definable recipes. Works with caged mobs so I think the entity walking event is really an entity-on-top-of event.

[The commit](https://github.com/BloodWorkXGaming/ExNihiloCreatio/compare/1.12...SirLyle:1.12).

![2017-09-04_21 54 40](https://user-images.githubusercontent.com/6723308/30041979-2aa30af0-91bc-11e7-9ff4-ab8330c47916.png)
![2017-09-04_21 55 47](https://user-images.githubusercontent.com/6723308/30041980-2be798d6-91bc-11e7-9795-17480832eece.png)

**Comment by BloodWorkXGaming** [comment]
Cool!
If you think you are done then just PR it in, then I'll merge it and read
over it.
Thanks ^^

**Comment by SirLyle** [comment]
There are a few scenarios I want to try to make sure it is stable. I will make a PR when I have satisfied my self QA.

**Comment by SirLyle** [comment]
Not sure if you've seen but I made the pull request.

**Comment by BloodWorkXGaming** [comment]
Merged the PR, thanks
