### ISSUE TITLE
[Suggestion] On nights (or in darkness) mushrooms grows on mycelium near barrel of witch water

### ISSUE THREAD

**Issue by KiBergMK** [BloodWorkXGaming/ExNihiloCreatio#203]
![htI8iYy](https://user-images.githubusercontent.com/48606321/55581986-04f4bd80-5727-11e9-9dea-e7742110f488.png)

**Comment by SirLyle** [comment]
Are you sure you submitted this to the correct ex nihilo mod? That barrel does not look like creatio's.

**Comment by KiBergMK** [comment]
> Are you sure you submitted this to the correct ex nihilo mod? That barrel does not look like creatio's.

I found this picture on the Internet and showed it as an example.

**Comment by SirLyle** [comment]
I don't think I will be adding this, as vanilla mechanics already allow for mushrooms to spread in darkness, and barrels already (by default) generate mushrooms while forming witch water.
