### ISSUE TITLE
[Suggestion] CraftTweaker support? 

### ISSUE THREAD

**Issue by mariodk** [BloodWorkXGaming/ExNihiloCreatio#207]
add CraftTweaker support

even editing repices dont work at all
or adding a Ore piece to a OreDict wont work
or rename any items or do anything with CraftTweaker at all

**Comment by SirLyle** [comment]
Could you please rephrase this in clear detailed manner using complete sentences.

**Comment by SirLyle** [comment]
I am closing this pending a more complete description. Most of the things you are requesting don't sound like things that would be done on Ex Nihilo's side.
