### ISSUE TITLE
Ex Compressum saw dust not being accepted by the composting barrel by default

### ISSUE THREAD

**Issue by CritFlaw** [BloodWorkXGaming/ExNihiloCreatio#208]
Minecraft - 1.12.2
Forge - 2808
Ex Nihilo - 0.4.1.2
Ex Compressum - 3.0.27

Composting Json - https://pastebin.com/WwjmWxqa
I added in the wood chippings entry beginning on line 6. 

By default, the dust is not accepted. The code in Ex Compressum references the oredict sawDust. The wood chippings still have that oredict entry. Possible conflict could be unidict.

**Comment by SirLyle** [comment]
The Ex Compressum code uses "dustWood" not "sawDust", if the oredict entry in-game is "sawDust" then you have another mod changing the oredict of the item and causing the issue.

My test using the latest creatio and compressum show that it works when JSON is disabled, and properly generates when JSONs are enabled

```
  "ore:dustWood": {
    "value": 0.125,
    "compostBlock": "minecraft:dirt:0",
    "color": "c77826"
  }
```

Please confirm that your woodchippings are really oredicted as "sawDust" and not "dustWood", if they are, check your crafttweaker/unidict scripts/configs to see if anything is messing with that oredict.

**Comment by CritFlaw** [comment]
They are oredicted as dustWood. I'm not sure if it's thermal or what exactly is causing the difference in oredict. It's in none of my scripts otherwise. Anyway, I will change its oredict.

**Comment by SirLyle** [comment]
`dustWood` is what is is suppose to be. If you delete CompostRegistry.json it should generate correctly.

**Comment by SirLyle** [comment]
As far as I can tell there is no issue on creatio's part, so I am going to close this. Re-open if there is an issue.
