### ISSUE TITLE
Aluminium vs. Aluminum Tconstruct smeltery

### ISSUE THREAD

**Issue by Andras32** [BloodWorkXGaming/ExNihiloCreatio#21]
Version:
MC 12.1
exnihilocreatio-1.12-0.1.3
TConstruct-1.12-2.7.2.19

Aluminium ore chunks are not recognized in the tinker's smeltery, I suspect this has to do with oredict oreAluminium and oreAluminum

**Comment by BloodWorkXGaming** [comment]
Fixed in the dev version, not released yet tho
