### ISSUE TITLE
Enhancement String Mesh anti conflicting Helper.

### ISSUE THREAD

**Issue by SirAron111** [BloodWorkXGaming/ExNihiloCreatio#210]
String mesh recipe needs to be a bit more special it overlaps with so many string recipes. Make it an X shape or something or add sticks to the sides.

**Comment by SirLyle** [comment]
Pretty sure both of your suggestions conflict with other mods default crafting recipes.

Making a recipe using vanilla ingredients that no other mod conflicts with is basically an impossible task. If someone is making a pack they are expected to use crafttweaker, if someone is just throwing mods together I would recommend using [NoMoreRecipeConflict](https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict).

It's also nearly impossible to be sure that you can detect recipe conflicts (not without registering last ... which would break crafttweaker). So resolving recipe conflicts for every single mod that may or may not exist is infeasible.

**Comment by SirAron111** [comment]
I am using craft tweaker and NoMoreRecipeConflict. And I made a custom recipe for the mesh because it conflicts with the Silk block from the Erebus mod. I was just thinking that the damn mesh uses a recipe made from 9 x purely made of the same material which is mostly used by mods that want to store large amounts of an item in block form and as a basic crafting recipe to make the mesh as the higher tier meshes have recipes using other materials and or the previous mesh just adding 2 sticks at the sides of the mesh recipe would fix at least this small conflict problem for Modpack makers who aren’t good enough to make custom recipes. (or for the case that some retarded player takes out the custom recipes scripts because they are too hard for him and then comes complaining he can’t craft a mesh because there is a silk block in the way seriously T.T why are people so stupid sometimes) Well np closed issue anyway.

**Comment by SirLyle** [comment]
I sympathizes with your issues with people not understanding that messing with script files might break things, though i would request you avoid insults even in the abstract. But the issue (conflicting recipes) is not trivial to fix, and just about any sensible recipe (important for the vanilla+one or two mods players) conflicts with something.
