### ISSUE TITLE
Sieve Efficiency 5 + Haste 2 glitch out sieving

### ISSUE THREAD

**Issue by Insane96** [BloodWorkXGaming/ExNihiloCreatio#213]
![2019-04-28_17 30 59](https://user-images.githubusercontent.com/7185104/56866607-74cf2e80-69db-11e9-87b8-c5485455b8eb.png)
After clicking 2 times (not counting the place click) the 3rd time the sieving progress gets to a negative number.
This as something to do with the type (byte) of `progress`: https://github.com/BloodyMods/ExNihiloCreatio/blob/1.12/src/main/java/exnihilocreatio/tiles/TileSieve.java#L48 ... Just change it to short ... or check if goes below 0.
45+45+45>127 ... RIP

**Comment by SirLyle** [comment]
Was discovered and fixed in the current dev branch.
