### ISSUE TITLE
Can you add Crafttweaker support?

### ISSUE THREAD

**Issue by developerfabi** [BloodWorkXGaming/ExNihiloCreatio#218]
It would be pretty nice if you could add crafttweaker support. Or any other easy way to configure the sifting recipes.

**Comment by SirLyle** [comment]
It should [already exist](https://github.com/BloodyMods/ExNihiloCreatio/blob/1.12/src/main/java/exnihilocreatio/compatibility/crafttweaker/Sieve.kt) and there are the JSON recipes which are easier than crafttweaker.

Duplicated #38.

**Comment by developerfabi** [comment]
Thank you very much for your answer and the link, it helped me out a lot! I didn't knew it existed.
