### ISSUE TITLE
JEI rendering bug of crucible heat souce.

### ISSUE THREAD

**Issue by GamyGamer** [BloodWorkXGaming/ExNihiloCreatio#220]
So... I don't know, if this is a bug for JEI, or this mod, but as you can see below there is some visual glitches:

![image](https://user-images.githubusercontent.com/49346764/57638810-d59b6100-75ae-11e9-822d-9207aad1f246.png)

**Comment by SirLyle** [comment]
This wouldn't be a JEI issue.

What version of creatio are you using. Do you have any other mods installed, particularly ones which change rendering? If this is a published modpack could you post a link to it.

**Comment by GamyGamer** [comment]
I were using the latest mod, which was flagged as "Release":

![image](https://user-images.githubusercontent.com/49346764/57695283-24e49e80-764e-11e9-850a-4fe44c57f5e8.png)


there is my list of my all mods:
![image](https://user-images.githubusercontent.com/49346764/57695049-8f490f00-764d-11e9-9dc4-f72bd8c17169.png)

And no, I have downloaded those mods separately.

**Comment by GamyGamer** [comment]
One quick note: It looks like this bug occur randomly, today it look normally

![image](https://user-images.githubusercontent.com/49346764/57729792-4fa71500-7697-11e9-9824-f4bdf4701bde.png)

**Comment by SirLyle** [comment]
The best kind of bug :/

Is it fairly consistent each game/day with if it works or not? Or is there maybe a nearby TESR when it is messed up (i.e. are there certain areas where it messes up)?

**Comment by SirLyle** [comment]
I am going to close this issue as it can't be reproduced. If you find a way to consistently reproduce this issue please open a new issue.
