### ISSUE TITLE
Sand does not work properly

### ISSUE THREAD

**Issue by CosmicQuail** [BloodWorkXGaming/ExNihiloCreatio#221]
Sand cannot be put into any sieves besides tier 1 string one, and does not drop anything even after hundreds of sand inputs. It is stopping my ex nihilo skyblock survival. I cannot get any drops from it so I cannot get ancient spores.

**Comment by SirLyle** [comment]
Are there any recipes using sand visible in JEI please upload your SieveRegistry.json file to pastebin and post a link here.

**Comment by CosmicQuail** [comment]
what is JEI and how do i find SieveRegistry.json?

**Comment by SirLyle** [comment]
JEI is a mod which lets you view recipes, creatio has support for it and it can be used to see what items drop from what blocks+meshes. SieveRegistry.json would be in <minecraft folder>/configs/exnihilocreatio and if enabled in <minecraft folder>/configs/exnihilocreatio/exnihilocreatio.cfg is used to customize the drops that different block+mesh combinations give.

**Comment by SirLyle** [comment]
When you have more information please open a new issue.
