### ISSUE TITLE
[Enhancement] Make JEI show more precice percentages

### ISSUE THREAD

**Issue by Insane96** [BloodWorkXGaming/ExNihiloCreatio#225]
Right now 2.5% chance for something is displayed as 2%

**Comment by SirLyle** [comment]
Which recipe category is not showing "2.5"? Some already handle more precision.

**Comment by Insane96** [comment]
In Sieving
![Immagine](https://user-images.githubusercontent.com/7185104/57979838-2255c080-7a23-11e9-862d-71fd89fdd691.png)

**Comment by SirLyle** [comment]
Updated version uploaded to curse.
