### ISSUE TITLE
Custom fluids in barrels being colourless

### ISSUE THREAD

**Issue by GamerwithnoGame** [BloodWorkXGaming/ExNihiloCreatio#226]
I've added some custom fluids via GregTech Community Edition using a script file (attached), and then used those fluids in a barrel transformation similar to the water-to-witchwater one (the luids used were grape juice and vinegar), however both fluids show up as colourless when inside the Ex Nihilo Creatio barrel.  The transformation still occurs, and once bucketed out it looks fine, but visually the mod doesn't seem to have picked up the colour from the script.

(Note: Attached files have been converted to txt format;  "_GT_Custom" was a .zs script file, and "FluidTransformRegistry" was a .json file)

[_GT_Custom.txt](https://github.com/BloodyMods/ExNihiloCreatio/files/3193916/_GT_Custom.txt)
[FluidTransformRegistry.txt](https://github.com/BloodyMods/ExNihiloCreatio/files/3193917/FluidTransformRegistry.txt)

**Comment by SirLyle** [comment]
A new version (0.4.3.1) has been pushed to curse.
