### ISSUE TITLE
[Request] Mekanism support

### ISSUE THREAD

**Issue by FnordMan** [BloodWorkXGaming/ExNihiloCreatio#23]
Any chance of getting official Mekanism support, namely for Osmium?

Added some entries to the json myself for the ingots but that's felt a bit hacky, official support would be nice. (not to mention my custom entries got removed recently during an update...)

**Comment by BloodWorkXGaming** [comment]
Your entries didn't get removed, however a recent update disabled json recipes by default to make it easier to provide new mod integration in updates

**Comment by Travis9x** [comment]
I second this motion:  official support for Mekanism would be awesome.  Same goes for Yellorium, such as for Big Reactors (and all offspring mods) mod.  :)

**Comment by kraft2004** [comment]
I "third" this. Would be very nice.

**Comment by SirLyle** [comment]
I've never played through mekanism (other players have always rushed it); is the only support Mekanism needs is Osmium ore pieces/chunks?

Do these lists look complete?

#### Actually Additions
- [x] Black Quartz

#### Applied Energistics / Applied Llamagistics
- [x] Sky Stone
- [x] Certus Quartz
- [x] Charged Certus Quartz

#### Big Reactors
- [x] Yellorium/Uranium

#### Integrated Dynamics
- [x] Menril Saplings

#### Mekanism
- [x] Osmium

**Comment by FnordMan** [comment]
Looks good here, the only ores that Mekanism uses are Copper, Tin and Osmium. (it can spawn salt in the world but that's not exactly required, there's other ways of getting that)

**Comment by Travis9x** [comment]
Yep, all Mekanism would need is Osmium.  The list for the other mods looks good, too.  🙂

**Comment by SirLyle** [comment]
If you guys wouldn't mind taking a look at [this branch](https://github.com/BloodWorkXGaming/ExNihiloCreatio/tree/crossmod) I've added cross mod support and would like your thoughts on the values (I've not really used Mekanism/Extreme Reactors before).

**Comment by SirLyle** [comment]
Added some cross mod support and set up the code to easily add more.

**Comment by darthvader45** [comment]
This would be greatly appreciated, as I use Geolosys for ore and to be perfectly honest I'm having a rough time finding autunite deposits for getting uranium clusters.  I need it for IE uranium slabs, which have a nice green color perfect for a military base hangar roof.  Speaking of which, I need to suggest things to BluSunrize and malte.
