### ISSUE TITLE
Recipes from FluidItemFluidRegistry.json do not have a JEI plugin

### ISSUE THREAD

**Issue by GamerwithnoGame** [BloodWorkXGaming/ExNihiloCreatio#230]
Currently, transformations from one fluid into another fluid in a barrel by addition of an item (found in **FluidItemFluidRegistry.json**)  do not appear in JEI and require a plugin.  

(Note: by default, the only such recipe that exists is the instantaneous transformation water to witchwater by adding ancient spores)

**Comment by SirLyle** [comment]
Fixed version uploaded to curse.
