### ISSUE TITLE
Flowing Lava (or Pyrotheum) don't give progressively reduced speeds for Crucible

### ISSUE THREAD

**Issue by Insane96** [BloodWorkXGaming/ExNihiloCreatio#232]
I don't know if it was in 1.10 but when lava wasn't the full block it would progressively give less speed to crucibles.

E.g. Lava flows for 4 blocks. The source blocks would give 3x speed as usual, the other ones would be _source_speed / max_flow_blocks * current_block_flown_. So E.g. with Lava would be _3x / 2.25x / 1.5x / 0.75x_ from the main block to the last flown.

**Comment by SirLyle** [comment]
I think that was in 1.10, and wasn't ever in Creatio. I can look at the feasibility of adding it.

**Comment by SirLyle** [comment]
I managed to make it reduce in a hopefully flexible manner, but had to round since the heat value has to be an integer amount (crucibles produce "heatrate" millibuckets per operation).

A new version has been pushed to curse.
