### ISSUE TITLE
[BUG] items not showing in crucibles

### ISSUE THREAD

**Issue by resinate** [BloodWorkXGaming/ExNihiloCreatio#234]
when making custom blocks to lava/liquid amounts, if amount of liquid is over 1000mb per item, the item shows up blank in NEI

**Comment by SirLyle** [comment]
Could you upload your json file so I can use it for testing.

**Comment by resinate** [comment]
heres an example

Working
  "minecraft:snow": {
    "fluid": "cryotheum",
    "amount": 1000
  },

Not Working
  "minecraft:snow": {
    "fluid": "cryotheum",
    "amount": 4000
  },

**Comment by SirLyle** [comment]
Fix merged.
