### ISSUE TITLE
[BUG]Mesh and sieve

### ISSUE THREAD

**Issue by totorich** [BloodWorkXGaming/ExNihiloCreatio#235]
Hi,

Impossible to put the mesh on the sieve for the last version of the mod. An idea plz?

**Comment by SirLyle** [comment]
Is your jar file named "Ex-Nihilo-Creatio-Mod-1.12.2.jar"? if so delete it and download the version from CurseForge; and never download anything from 9minecraft again.

**Comment by totorich** [comment]
ho yeah, thanks very much ^^
