### ISSUE TITLE
[Suggestion] Custom Meshes

### ISSUE THREAD

**Issue by SebastianBr11** [BloodWorkXGaming/ExNihiloCreatio#238]
It would be really cool, if you could add the ability to make Custom Meshes, where one can change the colour and add other drops to it.

**Comment by SirLyle** [comment]
This is planned for post 1.12 versions but is infeasible for the 1.12 version—meaning it would require rewriting the sieve's code, the rendering code, and changing how the sieve's metadata is serialized, while breaking every existing SieveRegistry.json file on every single modpack/users install.

Currently the color can be changed using texture packs, the name with lang files, and the drops can be changed in the SieveRegistry,json file, you are just limited to 4 total mesh types.

**Comment by SebastianBr11** [comment]
That's very good to know, looking forward to that.
