### ISSUE TITLE
Gravel not converting to sand with hammer

### ISSUE THREAD

**Issue by happybandit360** [BloodWorkXGaming/ExNihiloCreatio#239]
I have not edited the default HammerRegistry.json file, but gravel is not converting to sand when hit with a hammer, it is simply dropping gravel. Looking at the file, I can see where it should work, but it isn't.

Compressed gravel is turning to sand with a compressed hammer. I recognize ExCompressum is a separate mod, but I'm not sure if there is any crossover there like with the SieveRegistry

It's completely possible this is a result of another mod in my pack, but I was just wanted to check to see if this might be a known issue.

Thanks.

**Comment by SirLyle** [comment]
Can you upload you HammerRegistry.json file to pastebin and reply with the link. What hammer are you using? If it is the tinker's style hammer, is it "broken"? What mod version are you using?

ExCompressum has its own compressed hammer registry that is separate.

**Comment by happybandit360** [comment]
https://pastebin.com/Xg8g1KvL
I tried with both a wooden and iron hammer, both Ex Nihilo. Tinkers is not in the pack.
Mod version: exnihilocreatio-1.12.2-0.4

**Comment by SirLyle** [comment]
It's working on my test world with that version and your hammer file. Can you provide a list of what other mods you have installed? Do other hammer recipes work?

**Comment by happybandit360** [comment]
This is the mod list - https://docs.google.com/document/d/1ViYMtXI2G7-F9q-8fqrCD5eK7HJDxN5Xn9tY9CWFuIM/edit?usp=sharing

This seems to be the only thing not hammering correctly. It's not exactly a game breaker, but I can't see any reason it should be working.

**Comment by happybandit360** [comment]
I just realized what the issue probably is. I've set Dropt so gravel only drops gravel and not flint. I bet that is interfering with it. I'm sorry I've wasted your time with this.

**Comment by SirLyle** [comment]
One potential issue: it uses the "gravel" oredict instead of specifying vanilla gravel; do you have anything that might be modifying the oredict to remove that? Not sure if you have a mod which displays oredict names when you enable advan ...

NVM, that sounds like it.

**Comment by SirLyle** [comment]
I've not used dropt before, but if its possible to configure it to ignore certain tools you can try that (i.e. ignore the ex nihilo hammers).
