### ISSUE TITLE
Possible bug: Crucible Interaction with transfer nodes. 

### ISSUE THREAD

**Issue by FnordMan** [BloodWorkXGaming/ExNihiloCreatio#24]
These two screenshots will hopefully show what's going on. Looks like the crucibles take in rather too much cobble when being fed in some automated way. 
![2017-09-02_16 30 58](https://user-images.githubusercontent.com/7041560/29998912-517adc6e-8ffc-11e7-801a-8ac3fc29dab2.png)
![2017-09-02_16 31 06](https://user-images.githubusercontent.com/7041560/29998911-515d4f5a-8ffc-11e7-933d-424c0bbd9fc8.png)

Thermal Dynamics itemducts and Mekanism logistical transporters both do the same thing to a lesser degree. 

Running 0.1.3 here, just updated earlier this morning.

**Comment by BloodWorkXGaming** [comment]
Strange... Works with hoppers... Will look into it

**Comment by iTaeyeonKim** [comment]
![2017-09-04_23 22 28](https://user-images.githubusercontent.com/31522572/30038781-bf01d5d0-91c8-11e7-802b-b2fbaace6cdc.png)

same here but i got flying cobblestone

**Comment by iTaeyeonKim** [comment]
also this happens only when transfer pipe is using here, because on crucibles all kinds( wooden crucible, wooden barrel, stone barrel) actually it place all 64 blocks, not at once but rapidly, so 16000 mB is the highest number that can go

**Comment by BloodWorkXGaming** [comment]
Thanks for not being open source xu2... I am not setting a max stack size
of items, but rather I am calculating them dynamicly  depending on the
fluid to stone ratio, calculating one based on that might resolve the
problem...

However the main bug is not on my side here for them disrespecting that it
shouldn't force import something.

**Comment by BloodWorkXGaming** [comment]
alright, fixed it by adding a stack limit
