### ISSUE TITLE
Crucible reverts to unfired when placed over lava.

### ISSUE THREAD

**Issue by lsi5974** [BloodWorkXGaming/ExNihiloCreatio#242]
Baked an unfired crucible...several times lol and each time it was placed before and after the lava was placed, didnt matter, it reverted back to an unfired crucible.

Im playing in 1.12.2, forge version 14.23.5.2838 and using version 0.4.4 of the mod.

Thanks in advance for taking the time to check this out and thanks for the mod.

**Comment by SirLyle** [comment]
Could you please post a screenshot of you looking at the crucible with the F3 menu on? Could you also please provide a list of all the mods you have installed?

**Comment by lsi5974** [comment]
Sorry, was off for a while.  Pretty sure it was lava dynamics causing the issue, Ive removed that mod now and it seems to be working fine.

**Comment by SirLyle** [comment]
Interesting. Thank you for the update.

Edit: confirmed it is lava dynamics.

**Comment by SirLyle** [comment]
Okay I think I figured it out. LavaDynamics has a world smelting event which grabs blocks and check if they can be smelted. But it does not seem to handle metadata of blocks (unfired crucible is meta = 0, fired is meta = 1) so for the crucible it messes up.

[This function of theirs](https://github.com/kreezxil/Lava-Dynamics/blob/5b4bee45fda72ed3d6c63d7379d0b30cd111bcf9/1.12.2/src/main/java/com/eleksploded/lavadynamics/WorldSmelting.java#L71) does not check metadata.

I will open an issue on their github.

**Comment by eleksploded** [comment]
Just a heads up, this fix has been pushed on LD side. We all good now.

**Comment by lsi5974** [comment]
Nice, thanks all.
