### ISSUE TITLE
texture overrides dont work in stone crucibles

### ISSUE THREAD

**Issue by resinate** [BloodWorkXGaming/ExNihiloCreatio#243]
1.12.2 newest version released as of 6/22/2019 4pm cali time

  "actuallyadditions:item_solidified_experience": {
    "fluid": "xpjuice",
    "amount": 100,
	"textureOverride": {
      "name": "extrautils2:simpledecoative",
	  "meta": 1
    }
  }

**Comment by SirLyle** [comment]
are you sure

> simpledecoative

isn't suppose to be

> simpledeco**r**ative

?

**Comment by SirLyle** [comment]
Closing as not enough information has been provided to confirm that it is a bug with ex nihilo.
