### ISSUE TITLE
Crash on a forge+paperspigot server.

### ISSUE THREAD

**Issue by CrystalCurtain** [BloodWorkXGaming/ExNihiloCreatio#245]
Server crashed when startup.
and there is the crash-report.
Hope u can fix this.
THX!
(sorry for my Poor English)
 [ https://paste.ubuntu.com/p/TCyz7nPKqB/]( https://paste.ubuntu.com/p/TCyz7nPKqB/) 
(and The mean of Chinese:
server ticking loop.)

**Comment by CrystalCurtain** [comment]
I have solved the problem by change the java runtime version....
But why could it worked?
?_?

**Comment by SirLyle** [comment]
Without knowing what you changed from/to I can't speculate.

**Comment by SirLyle** [comment]
Closing as the issue is solved and not enough information has been provided to determine if there was an issue to begin with.
