### ISSUE TITLE
Crashing with current latest tinkers

### ISSUE THREAD

**Issue by Darkmega18** [BloodWorkXGaming/ExNihiloCreatio#25]
[B#349]  Description: There was a severe problem during mod loading that has caused the game to fail
[B#349]  
[B#349]  net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ex Nihilo Creatio (exnihilocreatio)
[B#349]  Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Trying to register a modifier with the name exnihilo_smashing but it already is registered
[B#349]  	at slimeknights.tconstruct.library.TinkerRegistry.registerModifierAlias(TinkerRegistry.java:467)
[B#349]  	at slimeknights.tconstruct.library.TinkerRegistry.registerModifier(TinkerRegistry.java:461)
[B#349]  	at exnihilocreatio.compatibility.tconstruct.CompatTConstruct.postInit(CompatTConstruct.java:19)
[B#349]  	at exnihilocreatio.ExNihiloCreatio.postInit(ExNihiloCreatio.java:98)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#349]  	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:609)
[B#349]  	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[B#349]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#349]  	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[B#349]  	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[B#349]  	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[B#349]  	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[B#349]  	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[B#349]  	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[B#349]  	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[B#349]  	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
[B#349]  	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#349]  	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[B#349]  	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[B#349]  	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[B#349]  	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[B#349]  	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[B#349]  	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[B#349]  	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[B#349]  	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[B#349]  	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:786)
[B#349]  	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
[B#349]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[B#349]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[B#349]  	at net.minecraft.client.main.Main.main(SourceFile:123)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#349]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#349]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#349]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Got slapped with this when I updated tinkers just today. For now I've disabled the modifier from being added in the config. Please take a look at what could be causing this. It says creatio, but I'm also using compressum along with this... not to mention all the other mods.

**Comment by HendrikJ79** [comment]
#https://github.com/SlimeKnights/TinkersConstruct/issues/3149

**Comment by YOYOK9** [comment]
Having the same issue
Crash report:
https://pastebin.com/ARK6y3u2

**Comment by Nathkt1** [comment]
Problem does not occur for earlier versions of ex nihilio, only on latest version of the mod

**Comment by BloodWorkXGaming** [comment]
Thanks, fixed it, was due to a change how modifiers work in the latest tinkers update.

**Comment by Darkmega18** [comment]
Excellent. :D

**Comment by YOYOK9** [comment]
When will the update be out?
