### ISSUE TITLE
ExhihiloCreatio crashes when I try to load my game

### ISSUE THREAD

**Issue by aussie4** [BloodWorkXGaming/ExNihiloCreatio#250]
I added exhihiloCreatio to my skyfactory 4 modpack and it crashes when I load it

**Comment by SirLyle** [comment]
Upgrade to one of the newer beta versions, and in the future when you report crashes provide more information so of it wasn't due to a known and fixed bug I could actually help.

**Comment by SirLyle** [comment]
If this isn't due to the already fixed issue I know of in SF4 (AE2 config) open a new issue with:

* what version you are using
* a pastebin link to your crashlog.
