### ISSUE TITLE
Crucible not returning filled terracotta bucket

### ISSUE THREAD

**Issue by winnetrie83** [BloodWorkXGaming/ExNihiloCreatio#252]
Hello there,

I discovered while playing in mc 1.12.2, that the crucible gives you a filled iron bucket(lava) when i use a terracottabucket from my own mod : https://github.com/winnetrie83/winnetriesexpansionmod
You can find the bucket code here:
https://github.com/winnetrie83/winnetriesexpansionmod/blob/master/src/main/java/com/winnetrie/winnetriesexpansionmod/items/ItemTerracottaBucket.java

I'm not the best coder, so if there is something i did wrong don't hesitate to tell me.
My terracotta bucket work fine in when filling and placing in the world

forge-14.23.5.2838
exnihilocreatio-1.12.2-0.4.5.1.jar
in MC 1.12.2

**Comment by SirLyle** [comment]
Please add a license to your mod. Is there a built version of your mod somewhere (e.g. Curse?).

I haven't had a chance to test but I suspect it might be from your bucket using net.minecraftforge.fluids.capability.wrappers.FluidBucketWrapper as its fluid handler. Is your mod able to properly interact with other (non ex nihilo) tanks?

Take a look at [ceramic's clay bucket](https://github.com/KnightMiner/Ceramics/blob/1.12/src/main/java/knightminer/ceramics/items/ItemClayBucket.java) it uses [its own wrapper](https://github.com/KnightMiner/Ceramics/blob/1.12/src/main/java/knightminer/ceramics/library/FluidClayBucketWrapper.java).

**Comment by winnetrie83** [comment]
Yes my mod is on curse: https://www.curseforge.com/minecraft/mc-mods/winnetries-expansion-mod
Well i just tested and it appears to be non compatible with any other fluidcontainer.
So that's my fault. I'm very srry to bother you. I should have checked it first.

**Comment by SirLyle** [comment]
That's okay; I have a label for these situations. I hope I was able to help you find the area you need to fix: I think if you implement your own bucket wrapper which gives your terracotta buckets instead of the forge wrapper it'll work.
