### ISSUE TITLE
Autosifter in WAILA shows negative values?

### ISSUE THREAD

**Issue by Insane96** [BloodWorkXGaming/ExNihiloCreatio#254]
![2019-08-04_12 48 11](https://user-images.githubusercontent.com/7185104/62422644-43d75780-b6b6-11e9-8c6d-40a6df4e8aa1.png)

**Comment by SirLyle** [comment]
That is intended; it can rotate either direction.

**Comment by SirLyle** [comment]
Closing as this is intended.
