### ISSUE TITLE
Made a modpack including exnihilocreatio. ore chucks do not exist for some reason.

### ISSUE THREAD

**Issue by Tankman222** [BloodWorkXGaming/ExNihiloCreatio#258]
I combined the mods from skyfactory 3 and sky factory 4 (because most of the sky factory 4 mods are hot garbage, but I like bonsai and they dont work on their own for some reason). almost everything worked fine until I made an auto sieve and stuff, got me some ore pieces aaand ore chunks cannot be crafted. is this a glitch or do I need to download something to get these?

**Comment by SirLyle** [comment]
The sky factory 4 craft tweaker scripts blindly modify remove all crafting recipes for ores, you will need to modify the scripts or re-add the recipes manually.
