### ISSUE TITLE
Crash/conflict with TConstruct

### ISSUE THREAD

**Issue by Travis9x** [BloodWorkXGaming/ExNihiloCreatio#26]
I know this involves two separate mods, so I am posting this crash on both mods' threads/pages.  Crash detail as follows:

[PasteBin link](https://pastebin.com/0Juv7Ght)

**Comment by SirLyle** [comment]
Try updating [Ex Compressum to v 3.0.6](https://minecraft.curseforge.com/projects/ex-compressum/files/2478266). Their release note is:

"Fixed crash due to Tinkers Construct API change."

And I could only get mine to crash by downgrading from 3.0.6.
