### ISSUE TITLE
TiC Crook has one part that doesn't affect the tool stats.

### ISSUE THREAD

**Issue by Insane96** [BloodWorkXGaming/ExNihiloCreatio#262]

**Comment by SirLyle** [comment]
Two of the parts are considered "handle"s and give their material property; but only one gives their stats; this is a limit of Tinker's Construct.

**Comment by Insane96** [comment]
But wait, in the (e.g.) excavator all the parts count up to the stats.

**Comment by SirLyle** [comment]
Good point; apparently I have to override a method. Fix released to curse.
