### ISSUE TITLE
Crash with latest /dank/null

### ISSUE THREAD

**Issue by p455w0rd** [BloodWorkXGaming/ExNihiloCreatio#266]
I have removed the `p455w0rd.danknull.util.DankNullUtils` class in favor of making the internal inventory just function as a normal IItemHandler inventory to outside handlers. This has created a crash and I wasn't aware the `DankNullUtils` class was being used.

Reported in p455w0rd/danknull#209

Fixed in #265

**Comment by SirLyle** [comment]
Thank you for trying to fix; since /dank/null is now a normal IItemHandler; the dependency has been removed completely.

A new version has been merged/pushed to curse.
