### ISSUE TITLE
Having B:doTinkersConstructCompat=false with Tinker's Construct installed breaks Ex Nihilo Creatio's JEI menus

### ISSUE THREAD

**Issue by Mummified316** [BloodWorkXGaming/ExNihiloCreatio#270]
When B:doTinkersConstructCompat=false in ExNihiloCreatio.cfg and Tinkers' Construct is installed none of Ex Nihilo Creatio's custom JEI recipe menus will show up.

**Comment by SirLyle** [comment]
Fix released to curse.
