### ISSUE TITLE
[Question] "Translations" cannot be used

### ISSUE THREAD

**Issue by 1335268492** [BloodWorkXGaming/ExNihiloCreatio#275]
Using "Translations" will cause "OreRegistry.json" to be unreadable

version.0.4.7.1 and version.0.4.1.2

**Comment by SirLyle** [comment]
Could you upload the json file you are trying to use? This sounds like a bug.

**Comment by 1335268492** [comment]
yes!
[OreRegistry.zip](https://github.com/BloodyMods/ExNihiloCreatio/files/3663929/OreRegistry.zip)

**Comment by 1335268492** [comment]
> 您可以上传要使用的json文件吗？这听起来像个错误。

yes! 
[OreRegistry.zip](https://github.com/BloodyMods/ExNihiloCreatio/files/3663937/OreRegistry.zip)

**Comment by SirLyle** [comment]
You need a comma after the dust entry. Try running your file through [this site (jsonlint)](https://jsonlint.com/) and seeing if it highlights any errors.

Fixing that seems to make it work on 0.4.7.1 at least.

**Comment by 1335268492** [comment]
> 灰尘进入后需要逗号。尝试通过[此站点（jsonlint）](https://jsonlint.com/)运行文件，看看它是否突出显示任何错误。
> 
> 修复该问题似乎至少可以在0.4.7.1上运行。

I'm sorry, I didn't notice that. I've been thinking about it for two days.

**Comment by SirLyle** [comment]
Not a problem (for me). JSONLint is a handy site to bookmark if you are working with a lot of json files.

Since this appears to be solved I will close this issue.
