### ISSUE TITLE
Crash when using Ex Nihilo Creatio silkworms to infest TFC leaves

### ISSUE THREAD

**Issue by alcatrazEscapee** [BloodWorkXGaming/ExNihiloCreatio#279]
(Quoted from https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/504)

> I was playing a modpack called Terrafirmacraft Reloaded 2 (still in development, currently available here: https://github.com/Verph/TerraFirmaCraft-Reloaded-2/releases). I expected to use a silkworm to infest leaves and acquire string, but the game crashed when the infested leaves attempted to spread to TFC leaf blocks. A similar bug occurs when using a silkworm directly on TFC leaves. I believe it has something to do with a "decay property," which the Ex Nihilo Creatio code can't locate in the TFC code.
> 
> Crash log: https://paste.dimdev.org/foxodataqu.mccrash
> latest.log: https://hastebin.com/ayetulecad.md

After looking at ExNihlo's code, it seems it already special-cases forestry's leaves, and it would be much appreciated if this could be expanded to special case TFC's leaves as well. Or, for a more general solution, just check if the block state property exists in the block state container before applying it.

**Comment by SirLyle** [comment]
Yes this should be fixed on my side, since it is possible there are other mods making leaf blocks without the properties.

**Comment by SirLyle** [comment]
Release 0.4.7.2 should fix the leaf properties issue.
