### ISSUE TITLE
Can you please add a way to aquire IC2 Iridium?

### ISSUE THREAD

**Issue by Lion4K** [BloodWorkXGaming/ExNihiloCreatio#28]
I tried asking the maker of JAOPCA to add this, but he's not willing to.
https://github.com/TheLMiffy1111/JAOPCA/issues/28#issuecomment-326795010

**Comment by Nodachi216** [comment]
If you use the SieveRegistry.json file you can add it yourself. That's kinda the point of the config files, so pack makers can customize their packs.

**Comment by Lion4K** [comment]
Thanks for the headsUP

**Comment by Lion4K** [comment]
Hm, one thing thou, where is that file?

My exNihilo folder config folder does not have that file.

**Comment by BloodWorkXGaming** [comment]
You have to enable json recipes in the config to be able to change them.
Was disabled recently to allow me to add new default recipes.

**Comment by Lion4K** [comment]
Hi, i've managed to add it, its working, gonna leave the code here in case you wanna add it to the mod or maybe someone finds it useful.

`    {
      "drop": {
        "name": "ic2:misc_resource",
        "meta": 2
      },
      "chance": 0.05,
      "meshLevel": 4
    },`
