### ISSUE TITLE
[suggestion] support for  Liquid to liquid  transformation in barrels

### ISSUE THREAD

**Issue by majijn** [BloodWorkXGaming/ExNihiloCreatio#29]
I tried to add a recipe in the FluidBlockTransformerRegistry file to transform an existing fluid in a barrel into another fluid by adding an item or block from my inventory and it's not working , instead of giving the fluid it just gives the missing texture , and I cant interact with the contents of the barrel once it's transformed.

**Comment by SirLyle** [comment]
I have a fork where I've added this ability added using json of the form:

    [
      {
        "inputFluid": "water",
        "reactant": {"name": "minecraft:redstone", "meta": 0},
        "output": "witchwater"
      }
    ]

If BloodWorkXGaming wants I can make a pull request.

**Comment by BloodWorkXGaming** [comment]
Ye sure, can't hurt, thank you ^^ will merge it together with the other PR
soon then.

**Comment by SirLyle** [comment]
My existing pull request now has the FluidItemFluid recipe type (I was already working on the same base).

**Comment by BloodWorkXGaming** [comment]
This now exists as well thanks to @SirLyle !
