### ISSUE TITLE
Gold sieving lowers thru higher level sieve.

### ISSUE THREAD

**Issue by Minecr4ck** [BloodWorkXGaming/ExNihiloCreatio#291]
Version exnihilocreatio-1.12.2-0.4.7.2.jar
Not sure if this is intentional..
When upgrading from metal to diamond sieve most materials either stay the same or increase in chance, except for gold. It goes from 20%-10% metal-diamond sieve.
Playing 3.2.51 PO3 Kappa mode  (It sounds like mod-pack author hasn't modified these settings.)
![Gold  Sieving](https://user-images.githubusercontent.com/26249745/75092554-81121280-553e-11ea-87a8-2544fe50fdcb.PNG)
![diamond sieving](https://user-images.githubusercontent.com/26249745/75092557-853e3000-553e-11ea-9555-bc9e64fb0cfc.PNG)

**Comment by SirLyle** [comment]
The modpack has either modified the settings or is using old defaults.

Current defaults for gravel should be ([code](https://github.com/BloodyMods/ExNihiloCreatio/blob/75f60692a4257a62ba9f6831866e456d8526ec9d/src/main/java/exnihilocreatio/recipes/defaults/ExNihilo.kt#L180))

Flint mesh 0.05
Iron mesh 0.075
Gold mesh 0.15
