### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by teoWei** [BloodWorkXGaming/ExNihiloCreatio#294]
I added Ex Nihilo : Creatio to my modpack and it crashes my game.
https://pastebin.com/bqR0LkVQ

**Comment by ToiletSalesman1** [comment]
I have the same problem on MacOS 10.15

**Comment by SirLyle** [comment]
That crash is being caused by "exnihiloomnia" not creatio. Completely different mod, and also not a mod that ever got out of alpha on 1.12.2.

**Comment by ToiletSalesman1** [comment]
My bad - not the same problem on my end as original report. My crash is caused by Creatio - I don't have Omnia.
https://pastebin.com/3XHHgRdv

**Comment by SirLyle** [comment]
That second crash log is caused by Ex Compressum, update to a version of Ex Compressum that isn't two years old.
