### ISSUE TITLE
game crashes when i try to load 

### ISSUE THREAD

**Issue by aquaticowl999999** [BloodWorkXGaming/ExNihiloCreatio#296]
im trying to get my game to load but it crashes with the error java.lang.NoClassDefFoundError: exnihilocreatio/tiles/TileCrucibleStone

**Comment by LucienAclantis** [comment]
Same problem here is the  Crash Report
https://paste.dimdev.org/asazekekah.mccrash
I didn't have this bug before I add  : 
**LagGoggles**
I tried other versions but don't work

**Comment by aquaticowl999999** [comment]
I don't even have lag goggles I got rid of it I'm confused by that

**Comment by SirLyle** [comment]
LagGoggles does weird stuff to events, I would suggest reporting this issue to them.

**Comment by SirLyle** [comment]
Looked on LagGoggles/TickCentral, [author claims to have fixed it](https://github.com/TerminatorNL/TickCentral/issues/1#issuecomment-619555918).
