### ISSUE TITLE
Thaumcraft NBT Data Issues.

### ISSUE THREAD

**Issue by JustLiam040** [BloodWorkXGaming/ExNihiloCreatio#297]
So im trying to create a modpack centered around using a combination of ex nihilo/thaumcraft to get resources. I have used content tweaker to create crushed arcane stone which can be sieved, this works fine when i set it to something simple such as emeralds etc, however i of course want to set it to farm the primal vis crystals. These crystals seem to identify via nbt data and tags; eg. 

Aspects: {
[0] {
amount:1
key "aer"
}
}

My question is, how would i go about adding this to a drop from a sieve, ive only ever seen one thread stating NBT data can be used however this seemed to break the JSON and stop me using the sieve altogether, any help would be much appreciated!

**Comment by JustLiam040** [comment]
Thought it would be useful if i added a screenie of the string i have tried. In my head i assumed i could simply paste in the items data in full and it would work off of that, this however wasnt the case and instead it had huge issues with the brackets that i simply couldnt figure out! :(


![Capture](https://user-images.githubusercontent.com/33065753/81019701-1a26a900-8e5f-11ea-8a67-79d7c2e902b6.PNG)

**Comment by SirLyle** [comment]
That particular example is breaking because you are using nested quotations.

The actual way you'll want to do it is something like so:

    {
      "drop": {
        "name": "thaumcraft:crystal_essence",
        "nbt": "{Aspects:[{amount: 1, key: 'perditio'}]}"
      },
      "chance": 0.75,
      "meshLevel": 1
    }

Use /enhandnbt while holding the item to get the exact string to past into the "nbt" tag.

**Comment by JustLiam040** [comment]
![Capture](https://user-images.githubusercontent.com/33065753/81046498-6d751780-8eb0-11ea-8363-00ba94821a90.PNG)


Sorry to comment again, the post was closed before i woke up so i was unable to read your reply. I chucked all of that into the thread and the sieve is still useable etc. However instead of giving me the crystals ive specified it seems to give me between 4-6 of any of the thaumcraft crystals, so now not only is it ignoring the key we have put in, it is now just giving me random amounts?

**Comment by JustLiam040** [comment]
![Capture](https://user-images.githubusercontent.com/33065753/81049891-fee78800-8eb6-11ea-88ed-e78f36a76dc1.PNG)

Final update, finally got it working using the NBT method you provided, however for some reason it doesnt like having the key in apostrophes, upon removing them it decides to work! :)
