### ISSUE TITLE
Only some sieve outputs working

### ISSUE THREAD

**Issue by Umbrial** [BloodWorkXGaming/ExNihiloCreatio#306]
After editing the .json for the mod to include drops for sieving crushed andesite and granite only a few sieving options will load in, they aren't even the same ones each time. 
If the whole thing stopped working I'd understand, but I can't figure why it picks random ones each load.

**Comment by SirLyle** [comment]
Could you post your json file to pastebin or attach it here? Please do not just copy paste it in.

**Comment by Umbrial** [comment]
I don't think I can do that from mobile, I can try attaching it here but with my computers browser problem it's hard to say.
Incase I can't, I know that what I did was copy crushed diorites entry, changed the name, and changed the drop to iron ore pieces.

**Comment by Umbrial** [comment]
...it's working now, I re-did the granite and andesite the same way I did it before but now it's working.
