### ISSUE TITLE
Slikworms

### ISSUE THREAD

**Issue by xKnightGamingx** [BloodWorkXGaming/ExNihiloCreatio#33]
In the latest beta of Ex Nihilo Creatio Silkworms when used drop players fps and kick them from the server, I remember this same bug back in 1.7.10 and thought it would be fixed but it seems to have returned. I have no screenshots or logs for this as when this happens players tell me after they drop fps and crash to the multiplayer screen

**Comment by BloodWorkXGaming** [comment]
Well, they are TESRs and send the Nbt quite often, so not really light on
the performance.
Just don't have 200000000000000 of them.

**Comment by xKnightGamingx** [comment]
It's happening when they just use 1 at a time

**Comment by BloodWorkXGaming** [comment]
Well, do you have some kind of log so I can investigate it?

**Comment by xKnightGamingx** [comment]
as soon as my staff member gets on, I'll see if he's got one

**Comment by SirLyle** [comment]
Perhaps instead of sending the nbt with the state repeatedly, if only the end time is sent, the client could then calculate the current state to render based on that (`(final time - current time) / total time`).

**Comment by BloodWorkXGaming** [comment]
slight problem there, you can't rely on the time to be the same on both.
One possible thing to do is to lower the amount of packets to a minimum to keep it in sync every few seconds.

**Comment by SirLyle** [comment]
A single infected leaf block produces a constant 20 block updates / tick (in F3) while it is transforming, That should be a zero, and it's a small change to make it 0.

[Video](https://gfycat.com/gifs/detail/ThoroughElementaryAfricanrockpython) of me testing a FastTESR + change in progression along with this block update change. Still get updates from spreading, but there's no escaping that. I consider my computer surviving the test to be a success.

**Comment by Tencao** [comment]
I've also done a PR which should resolve a lot of the issues people are experiencing with Infested Leaves, especially in highly dense areas.

**Comment by SirLyle** [comment]
For record purposes Tencao's PR is PR #45.

**Comment by SirLyle** [comment]
Pull Request #45 should greatly improve FPS.
