### ISSUE TITLE
[suggestion] Add crushed/gravel variants for andesite/diorite/granite; and also add kaolinite.

### ISSUE THREAD

**Issue by majijn** [BloodWorkXGaming/ExNihiloCreatio#35]
crushed variants of the other stones would mean modpack creators would be able to use them in case they want certain materials to not be accessible/as easily accesible from just normal gravel/sand/dust sifting

especially given how the rocks already drop from sifting dirt

I propose kaolinite should be another item needed for crafting the crucible clay (instead of just clay and bonemeal by themselves), perhaps crafted by adding crushed granite to a barrel of witchwater or sifting the crushed granite.

**Comment by SirLyle** [comment]
While I'm not sure about making the porcelain process grindier/pseudo-realistic, seems more like something a modpack could add if it fit a specific theme. I would suggest having granite be crushed down into vanilla red sand (with or without an intermediate step).

**Comment by majijn** [comment]
I just made a fresh skyblock world , just to see how mucch stuff I got by the time I obtained enough items for a crucible, and it took me 1.08 hours (says minecraft statistics page) and I had 8 clay, 7 bonemeal, and 25 granite pebbles, and one ancient spore.

the toughest part is definitely the witch water (it could easily be just water, after all clay can be made from just dust and water)

Im more suggesting this to actually add a use for these pebbles which otherwise dont have a use at all (and also because just adding bonemeal to clay to make a crucible  breaks my suspension of disbelief a touch more than the other things in the mod)

though making red sand from granite... is an idea I can get behind because red sand is rather hard to obtain otherwise, and it's definitely a cool block.

**Comment by BloodWorkXGaming** [comment]
Added the other crushed stones with 50cf56a75a6209444f30b1680087b071edff9399 but don't really see a point in adding kaolinite
