### ISSUE TITLE
Stone axles can be used as fuel.

### ISSUE THREAD

**Issue by majijn** [BloodWorkXGaming/ExNihiloCreatio#36]
they show up on JEI as being able to be used as fuel. i'm guessing this is unintentional.

**Comment by BloodWorkXGaming** [comment]
As furnace fuel or as crucible fuel?

**Comment by majijn** [comment]
furnace fuel

**Comment by majijn** [comment]
smelts 1.5 items

**Comment by SirLyle** [comment]
I am unable to insert axles into furnaces. Do you have other mods installed? Are you using crafttweaker to add fuels?

**Comment by BloodWorkXGaming** [comment]
Uh, might have fixed that bug already, just didn't release a curse version
for it or closed the issue report

SirLyle <notifications@github.com> schrieb am Mi., 1. Nov. 2017, 04:50:
