### ISSUE TITLE
Crash when a cow stands on top of a barrel (Cannot create a fluidstack from a null fluid)

### ISSUE THREAD

**Issue by Captain-John-Price** [BloodWorkXGaming/ExNihiloCreatio#37]
this crash report will explain to you

[crash-2017-10-01_21.49.13-server.txt](https://github.com/BloodWorkXGaming/ExNihiloCreatio/files/1347162/crash-2017-10-01_21.49.13-server.txt)
[crash-2017-10-01_21.38.50-client.txt](https://github.com/BloodWorkXGaming/ExNihiloCreatio/files/1347163/crash-2017-10-01_21.38.50-client.txt)

**Comment by SirLyle** [comment]
What mods do you have installed?

For some reason I thought fluid milk was added by forge, that's what i get for only testing with the optional dependencies (Tinker's) installed.

I guess now there is the choice of adding a milk fluid or just having the milking recipe not work if no other mod adds it. My [existing PR](https://github.com/BloodWorkXGaming/ExNihiloCreatio/pull/34) has been updated with a check before trying to fill the tank for any fluid (will be more flexible for bad user configs too).

**Comment by SirLyle** [comment]
Should've been fixed by commit [27fca082b702134c650f81071ecad60b28c8c3fb](https://github.com/BloodWorkXGaming/ExNihiloCreatio/commit/27fca082b702134c650f81071ecad60b28c8c3fb)
