### ISSUE TITLE
[Suggestion] Boom, fixed your Crucibles

### ISSUE THREAD

**Issue by Rocky28447** [BloodWorkXGaming/ExNihiloCreatio#4]
Up to you whether or not you want to use it. I personally like this look much better than the thicker design as it more closely resembles the one from the original Ex Nihilo. I'll send you the JSON if you want but it's up to you.

![image](https://user-images.githubusercontent.com/26193486/29154860-7a89adc8-7d65-11e7-8a2b-546804ff8e98.png)

**Comment by Rocky28447** [comment]
Also, there seems to be a bug with filling/emptying buckets from Crucibles.

**Comment by BloodWorkXGaming** [comment]
Sorry, but I like the thicker model better, as it makes more sense to have thicker walls when you store molten stone in something.

And the bug with the buckets, could you please elaborate? Taking fluids out works in for me, and putting lava back in is not supported (not not make problems with the current smelting process when there is a different block smelting). Are you sure you were not in creative when taking the fluid out with a bucket?

**Comment by Rocky28447** [comment]
I was in creative. Why can't you take lava out of a Crucible while in creative?

**Comment by BloodWorkXGaming** [comment]
you can, put the bucket won't get filled up, that is vanilla minecraft.
In creative a bucket will never change state, so when you try to pick up water with a empty bucket the bucket will stay empty.

**Comment by Rocky28447** [comment]
Oh, that's strange.

I also had another thought:
Would it be possible to make the look of Crucible configurable?

**Comment by BloodWorkXGaming** [comment]
AFAIK you can the models of blocks in a texture pack

Rocky28447 <notifications@github.com> schrieb am Do., 10. Aug. 2017, 19:27:

**Comment by Rocky28447** [comment]
Yes however the thin crucibles require changes to client.renderers.RenderCrucible, and you can't do that in a resource pack.

**Comment by BloodWorkXGaming** [comment]
if you still want this to be in I you could send me the jsons and I'll try to see whether it works

**Comment by Rocky28447** [comment]
Currently on vacation right now and don't have access to the modified
Jsons, though it didn't take that much modification and I can most likely
replicate within an hour in the next few days. if not, I will send them
when I get back this Sunday.

**Comment by Rocky28447** [comment]
Alright, here they are. This should be everything needed.

Lines 45 - 48 in client.renderers.RenderCrucible must be changed to this:
https://pastebin.com/V1vFUnqD

Here are the textures:
![crucible_bottom](https://user-images.githubusercontent.com/26193486/29785532-f4676a60-8bf5-11e7-974e-397dbc24c2f3.png)
![crucible_bottom_raw](https://user-images.githubusercontent.com/26193486/29785529-f4646b94-8bf5-11e7-89ac-d0e211231fa2.png)
![crucible_side](https://user-images.githubusercontent.com/26193486/29785531-f4669f90-8bf5-11e7-92f4-7fcc9a02d704.png)
![crucible_side_raw](https://user-images.githubusercontent.com/26193486/29785533-f468a560-8bf5-11e7-8474-4408b2fc5f1b.png)

Here are the Jsons:
[jsons.zip](https://github.com/BloodWorkXGaming/ExNihiloCreatio/files/1257690/jsons.zip)

**Comment by BloodWorkXGaming** [comment]
Welp, better late then never, but I finally got around to implementing this. ^^
