### ISSUE TITLE
crucibles causing too many chunk redraws

### ISSUE THREAD

**Issue by majijn** [BloodWorkXGaming/ExNihiloCreatio#41]
is there any way to disable the redraws or the insides rendering client side? 

or perhaps could a second crucible that's covered be added to the mod (perhaps with it own recipes for modpack

**Comment by BloodWorkXGaming** [comment]
I don't think there is any way to prevent that, but something like a tape
you could wrap around it to prevent it or something might be worth doing.

majijn <notifications@github.com> schrieb am Sa., 28. Okt. 2017, 03:10:

**Comment by SirLyle** [comment]
Real world crucibles often come with lids, could possibly do that instead of tape so it makes some thematic sense.

**Comment by majijn** [comment]
that's more what I was thinking, yeah.  would it be possible for the crucible with a lid to have its own recipes?

**Comment by BloodWorkXGaming** [comment]
Ye possible indeed, just not sure yet whether it is viable to make it as
the same block or whether it has to be a different one

majijn <notifications@github.com> schrieb am Sa., 4. Nov. 2017, 09:22:

**Comment by SirLyle** [comment]
Do we also want to investigate moving all the TESRs to forge's Fast TESRs?

**Comment by BloodWorkXGaming** [comment]
Kinda looked into it already, it's not entirely possible.
Or at least I didn't manage to do it with my limited OpenGL knowledge.
Some we maybe could transfer to there.

SirLyle <notifications@github.com> schrieb am Sa., 4. Nov. 2017, 21:12:

**Comment by SirLyle** [comment]
So I have converted Barrels/Leaves/Crucibles to FastTESRs and removed all the chunk updates from them (other than infested leaves spreading). The rotational stuff is a little more complex.

If people want to test [the branch](https://github.com/BloodWorkXGaming/ExNihiloCreatio/tree/RenderingAdjustment), it should be nearly ready to be pushed to main/curse.

**Comment by SirLyle** [comment]
Pull Request #45 should greatly reduce chunk redraws.
