### ISSUE TITLE
[Suggestion] support for specifying secondary outputs in config files when processing ores

### ISSUE THREAD

**Issue by majijn** [BloodWorkXGaming/ExNihiloCreatio#43]
say , if I wanted to add an iron ore that when crushed would give say, sulfur , when crushed in a pulverizer or some such, would there be a way to make that happen on your mod's end?

**Comment by SirLyle** [comment]
That would have to be done as a recipe for what ever machine you are using to do the processing.

**Comment by BloodWorkXGaming** [comment]
Not really, as there is no general forge registry for registering crushing
recipes or something like that.
If I understand correctly what you mean, we would have to add crushing
support for all those mods on its own.

majijn <notifications@github.com> schrieb am Mo., 6. Nov. 2017, 00:18:

**Comment by majijn** [comment]
ah, that wont do then, yeah, i'll have  to find another mod i can do it on then

(tho if you end up adding the crusher machine you had been doing it could be used there)

thanks for the swift response! appreciate it.

edit: it just occurred to me to try adding the items I wanted to have secondary outputs as a siftable, ill see if that works how I want it to!
edit2: either I added the source item wrong, or sifting doesnt accept non-blocks, either way it didn't work =(, guess ill have to find another way.

**Comment by SirLyle** [comment]
Correct sieves can only sift blocks—though it might be cool to make metallic dust blocks (9x powdered metal) which could be sifted or smelted directly into blocks.

Currently Ex Nihilo should be registering ore chunks in the ore dict, so any other mod's machine which can handle oredicted ores should give you their secondary outputs.
