### ISSUE TITLE
[Suggestion] add option to specify oredict entries in oreregistry.json

### ISSUE THREAD

**Issue by majijn** [BloodWorkXGaming/ExNihiloCreatio#44]
just so that items can have names that dont have to be exactly like the oredict entry for the item to be recognised by other mods.

**Comment by BloodWorkXGaming** [comment]
Probably not a bad idea, there are a few thinks that should be improved in
the ore registry tbh ^^

majijn <notifications@github.com> schrieb am Mo., 6. Nov. 2017, 00:20:

**Comment by SirLyle** [comment]
While I agree that the registries could be greatly improved: in the mean time if you need this capability crafttweaker can be used to register items into whatever oredict entry you want.

**Comment by BloodWorkXGaming** [comment]
This got added just now, you can now specify the oredict name in the json with "oredictName": "nameblabla" but there will still be the different basenames, like pice, dust, ore, etc which can be configured in the main config.
