### ISSUE TITLE
Can't sift after JSON addition

### ISSUE THREAD

**Issue by the-pieman** [BloodWorkXGaming/ExNihiloCreatio#46]
So, I want to make Sand able to drop Yellorium dust (from Extreme Reactors) when being sifted. I activated the recipe JSONs and added these lines to the 'Sand' section of the sieve registry.

https://pastebin.com/9qEjQvxm

It looked fine to me so I saved the edited JSON file and started minecraft up. However I ran into an issue when I went to test my change. I placed down a brand-new sieve and applied a new Diamond Mesh (the stage I selected) but when I went to sift some sand, my character made the usual 'right-click' hand motion but the sand didn't go into the sieve.

Tried it with other meshes and materials but same effect, I couldn't sift anything. Disabling the extended JSONs in the misc config of Creatio and restarting Minecraft, I could sift again, but (obviously) I lacked the recipe to sift for Yellorium.

Did I do something wrong when I applied the code? What can I do to fix this? I'd like to be able to add new recipes and still be able to use the sieves (obviously). Thank you in advance for any help.

**Comment by SirLyle** [comment]
Definitely sounds like you had an invalid JSON file. Can you upload the entire JSON file and not just the snippet.

**Comment by the-pieman** [comment]
Here is what it looked like before I made any changes.

https://pastebin.com/gScjiDxt

**Comment by SirLyle** [comment]
I meant could you post your modified json so I can see if you had valid json.

Edit: JSON not Jon, silly mobile.

**Comment by the-pieman** [comment]
Gotcha, sorry.

https://pastebin.com/QiKBViz2

Though I think I may have noticed what I did wrong, now that I look at it a couple days after. I may have added a comma at the final closing bracket when I wasn't supposed to. That may be the case, but if you can find something else wrong, let me know.

Forgot the most important rule of coding. If you get frustrated, leave it and look at it again later.

UPDATE: I tried running it after removing the comma and had the same issue, so that wasn't the culprit.

**Comment by SirLyle** [comment]
You need a comma before your yellorium entry. Each entry is in a list with the others, i.e.:

This
```
    {
      "drop": {
        "name": "minecraft:prismarine_shard",
        "meta": 0
      },
      "chance": 0.02,
      "meshLevel": 4
    }
    {
      "drop": {
        "name": "bigreactors:dustmetals",
        "meta": 0
      },
      "chance": 0.02,
      "meshLevel": 4
    },
```

Should be:

```
    {
      "drop": {
        "name": "minecraft:prismarine_shard",
        "meta": 0
      },
      "chance": 0.02,
      "meshLevel": 4
    },
    {
      "drop": {
        "name": "bigreactors:dustmetals",
        "meta": 0
      },
      "chance": 0.02,
      "meshLevel": 4
    }
```

Edit, also the most up to date Ex Nihilo added BR support, not sure when it's getting pushed to Curse.

**Comment by the-pieman** [comment]
Ahhhhh, it _was_ the comma, but it needed to be moved, not _re_moved... Thanks for your patience with my ridiculously simple bungle. Glad this community is so helpful.

**Comment by SirLyle** [comment]
No problem, glad it wasn't a bug.

**Comment by BloodWorkXGaming** [comment]
And this is why we need yaml :P

SirLyle <notifications@github.com> schrieb am Mi., 22. Nov. 2017, 21:54:

**Comment by SirLyle** [comment]
Agreed, JSON failed at its mission of being human-friendly.
