### ISSUE TITLE
Ore piece to Ore chunks

### ISSUE THREAD

**Issue by Girugamessho** [BloodWorkXGaming/ExNihiloCreatio#47]
I was not able to craft ore chunks with ore piece, tried 2x2 and 3x3 as well as recipe not existing in JEI

**Comment by SirLyle** [comment]
Are you playing a mod pack? If so which one?

Do you have any other mods installed?

Can you post a screenshot of the crafting table? If you have JEI can you view the ore chunk recipe?

**Comment by brisingraerowing** [comment]
For me, the recipe is a backwards 7 with four pieces on the left side. e.g.
(x is an ore piece, - is an empty slot)
x x -
x - -
x - -

I think the intention was for a 2 x 2 recipe but it got messed up somehow.

**Comment by SirLyle** [comment]
Sounds like you have UniDict installed, it messes with a lot of recipes for things which use the oredict properly.

**Comment by brisingraerowing** [comment]
I might. I'll have to check. That's from a pack I am working on a bit. Not really sure what mods I want in it yet (I do know I want Tech and Magic paths to work on, along with some exploration stuff [in additional dimensions]. And I need is a way to make custom portals to those dimensions for 1.12.2. Can't figure out that one as I don't know any mods that do that).

**Comment by BloodWorkXGaming** [comment]
Can't replicate, closing for now, feel free to reopen with more info.

**Comment by jmac460** [comment]
more info, happens to me too

**Comment by SirLyle** [comment]
That's not exactly more info.

Do you have other mods installed, if so which ones? Do you get the same backwards 7 recipe?

**Comment by BloodWorkXGaming** [comment]
Ye, we already figured our it is unidict, talked to wanioncane about how to
fix it and I know how to do it at some point, he says there should be a way
to blacklist recipes from the unifying

SirLyle <notifications@github.com> schrieb am So., 18. Feb. 2018, 03:58:
