### ISSUE TITLE
Wooden Crucible

### ISSUE THREAD

**Issue by MoJoCashem** [BloodWorkXGaming/ExNihiloCreatio#48]
Wooden Crucible and Heavy sieve have the same recipe. Ex nihilio Crucible and Ex compressum sieve

**Comment by majijn** [comment]
I use [nomorerecipeconflict](https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict) to 

thought, to be honest, the ex compressum crucible I seem to recall is more immediately useful as it only holds one bucket's worth and you can use it for water + block recipes (such as the one for clay)

**Comment by BloodWorkXGaming** [comment]
It indeed is more useful ^^ I added mine before I noticed ex compressum had
one ^^

majijn <notifications@github.com> schrieb am So., 3. Dez. 2017, 17:25:
