### ISSUE TITLE
As a mod author, what can I do to support Creatio?

### ISSUE THREAD

**Issue by ChiriVulpes** [BloodWorkXGaming/ExNihiloCreatio#49]
I have a finished mod which I made with the intention of it being good for skyblock, and would like to add drops from my mod to sieves (when Creatio is present, of course). Is there an API I can use to do this?

**Comment by BloodWorkXGaming** [comment]
There is not 100% a own API package, but in the regestries package is most
of the stuff you need to add recipes.

Mackenzie McClane <notifications@github.com> schrieb am Mi., 13. Dez. 2017,
01:13:

**Comment by ChiriVulpes** [comment]
Thanks, that was what I needed.

**Comment by SirLyle** [comment]
Take a look at [these compat classes](https://github.com/BloodWorkXGaming/ExNihiloCreatio/tree/1.12/src/main/java/exnihilocreatio/recipes/defaults). They get called from [our registry manager](https://github.com/BloodWorkXGaming/ExNihiloCreatio/blob/1.12/src/main/java/exnihilocreatio/registries/manager/CompatDefaultRecipes.java).

Edit: too slow.

**Comment by ChiriVulpes** [comment]
If you guys have the time, would you mind helping me with something? I have the support for Creatio implemented, but I can't get it to compile/run... (I assume it's an issue with my build.gradle file, because I have no real idea what I'm doing with it; just winging it based on other repos I see and the comments in the default file)

This is the error I'm getting:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':provided'.
> Could not find exnihilocreatio:exnihilocreatio:1.12-0.1.5.
  Searched in the following locations:
      http://files.minecraftforge.net/maven/exnihilocreatio/exnihilocreatio/1.12-0.1.5/exnihilocreatio-1.12-0.1.5.pom
      http://files.minecraftforge.net/maven/exnihilocreatio/exnihilocreatio/1.12-0.1.5/exnihilocreatio-1.12-0.1.5.jar
      https://repo1.maven.org/maven2/exnihilocreatio/exnihilocreatio/1.12-0.1.5/exnihilocreatio-1.12-0.1.5.pom
      https://repo1.maven.org/maven2/exnihilocreatio/exnihilocreatio/1.12-0.1.5/exnihilocreatio-1.12-0.1.5.jar
      https://libraries.minecraft.net/exnihilocreatio/exnihilocreatio/1.12-0.1.5/exnihilocreatio-1.12-0.1.5.pom
      https://libraries.minecraft.net/exnihilocreatio/exnihilocreatio/1.12-0.1.5/exnihilocreatio-1.12-0.1.5.jar
      file:/C:/Users/Mackenzie/.gradle/caches/minecraft/deobfedDeps/exnihilocreatio/exnihilocreatio/1.12-0.1.5/exnihilocreatio-1.12-0.1.5.pom
      file:/C:/Users/Mackenzie/.gradle/caches/minecraft/deobfedDeps/exnihilocreatio/exnihilocreatio/1.12-0.1.5/exnihilocreatio-1.12-0.1.5.jar
      file:/C:/Users/Mackenzie/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.1.2555/snapshot/20171003/exnihilocreatio-1.12-0.1.5.jar
      file:/C:/Users/Mackenzie/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.1.2555/snapshot/20171003/exnihilocreatio.jar
  Required by:
      yuudaari.souls:souls:1.12.2-1.0.0-cbb5870
```

And this is the repo: https://github.com/Yuudaari/Souls

I have the `provided` line commented out currently because that's what makes it not work. I tried all of the dependency types as well, deobfCompile, compile, etc, but they all throw basically the same error. I assume I'm missing something really simple but I can't figure it out.

Thank you for your time.

**Comment by BloodWorkXGaming** [comment]
You don't seem to have the blame jared maven as a dependency

**Comment by ChiriVulpes** [comment]
Aha, thanks, that helped a ton! I didn't realise that libs/ was separate from compilation, and that I needed to reference a maven. Once I referenced that the error changed to not referencing the mavens of Creatio's dependencies, so all I needed to do was copy those mavens from your build.gradle. It works!

Thanks again!

**Comment by ChiriVulpes** [comment]
I know I said this was working but turns out it actually doesn't... Idk how I managed to not test it or something.

https://github.com/Yuudaari/soulus/blob/master/src/main/java/yuudaari/soulus/common/compat/ExNihiloCreatio.java

Do you guys see any issue with this? The blocks aren't even siftable with the flint mesh...
It's called in postInit, and it does it for sure, I've tried logging in here. Afterwards I also tried logging the results:
```java
for (Siftable s : ExNihiloRegistryManager.SIEVE_REGISTRY.getDrops(new BlockInfo(Blocks.DIRT, 0))) {
	Logger.info(s.getDrop().getItem().getRegistryName().toString());
}
```
And my recipes appear. It's almost like the list is being reset after I'm done, but where would I use this api besides postInit?

[edit]: nvm, I figured it out!

**Comment by BloodWorkXGaming** [comment]
Depending on the json recipes config, they might be cleared again and only
read from the json file. There  is a event that gets called after that, so
subscribe to that and you can add of then

Mackenzie McClane <notifications@github.com> schrieb am Mi., 20. Dez. 2017,
02:18:
