### ISSUE TITLE
API Request: RegistryReloadEvent

### ISSUE THREAD

**Issue by blay09** [BloodWorkXGaming/ExNihiloCreatio#5]
This event existed in Adscensio for 1.10.2, but was missing in the 1.11.2 branch, which is probably why it's gone now.

See https://github.com/MikeLydeamore/ExNihiloAdscensio/issues/92 for original issue and https://github.com/MikeLydeamore/ExNihiloAdscensio/commit/144f367f582e85875783ee61ae3cd7987a3c99b7 for original implementation.

**Comment by BloodWorkXGaming** [comment]
Thanks for the heads up, tried to copy over most of the important missing
1.10->1.11 changes, will add it back in next version.

BlayTheNinth <notifications@github.com> schrieb am Mo., 14. Aug. 2017,
20:32:
