### ISSUE TITLE
[1.12.2] Recipes not using oredict but localised names

### ISSUE THREAD

**Issue by Morpheus1101** [BloodWorkXGaming/ExNihiloCreatio#50]
In the pack im developing i have worldgen in terms of stone done via a different mod that overrides the default minecraft stone, so the only stone types from default Minecraft are Andesitre, Diorite & Granite, the diff stone varients i do have, some are ore dict'd as cobblestone, however the recipe/requirement for the hammer is specifically minecraft:cobblestone

**Comment by BloodWorkXGaming** [comment]
Sorry for getting back to you so late, however the recipes is already using oredict
https://github.com/BloodWorkXGaming/ExNihiloCreatio/blob/6df45179c621b78ff4b3e57ae31b4c50d84e85c9/src/main/resources/assets/exnihilocreatio/recipes/hammer_stone.json#L14

or do you mean something different?

**Comment by Morpheus1101** [comment]
ummm...tbh im not even sure what i was referring to now, i suspect the issue was more in the worldgen mod for stone etc nothing was ore dict'd for cobblestone, but looking at the hammer now its aok, but im going to close this this since i dont fully recall the intent with it now.
