### ISSUE TITLE
Osmium Piece (from Mekanism) [Suggestion]

### ISSUE THREAD

**Issue by MiamiCenterPL** [BloodWorkXGaming/ExNihiloCreatio#53]
Hello!
Can you add Osmium Piece and Ore Chunk to the mod (Adding ability to melt down it in Tinkers' Construct Smeltery would be great too) seems like you forgot about it :)

Happy new year <3

**Comment by SirLyle** [comment]
Mekanism support has already been merged in, the chunk is registered as oreOsmium so if you have a mod which adds the molten osmium/parts (e.g. Moar Tinkers) it will be usable.

Duplicate #23 .
