### ISSUE TITLE
[Suggestion] Integration with Better With Mods gearboxes/mechanical power

### ISSUE THREAD

**Issue by SeriousCreeper** [BloodWorkXGaming/ExNihiloCreatio#54]
Heya,

it would be awesome if the mechanical power (gearboxes, axles, windmills, etc) from Better With Mods could be used to power the auto sieves and such. Just wondering if that would be a possibility! 

Cheers,
SC

**Comment by maham** [comment]
@Kiyaku While waiting for the feature the mod Better With Engineering adds this.

**Comment by BloodWorkXGaming** [comment]
ye, this mod adds this feature, not gonna bother implementing it then on here. https://minecraft.curseforge.com/projects/better-with-engineering
