### ISSUE TITLE
[Request] 1.12.2 Allow FluidBlockTransformerRegistry to use modded liquids.

### ISSUE THREAD

**Issue by gkuba** [BloodWorkXGaming/ExNihiloCreatio#55]
I would like to be able to use liquids from other mods in the barrel block transformations for example Resonant Ender and glowstone to make end stone. 

I have tried using the fluid name already and full mod:id  and it didn't work. 
works just fine as lava though.

**Comment by SirLyle** [comment]
It should be able to use modded fluids. What is the json you attempted to use? Note: fluids don't have a mod:id style name, they all share a registry.

This worked for me:
```
  {
    "fluidName": "ender",
    "input": {
      "name": "minecraft:glowstone_dust",
      "meta": 0
    },
    "output": {
      "name": "minecraft:end_stone",
      "meta": 0
    }
  }
```

Note the "fluid" name may be different from the in-world fluid block, also fluids do not have "mod:id" forms as they aren't associated with a specific mod. Blame the Thermal devs for their names not matching.

If you have COFH core installed (sounds like you do): hold a bucket of the fluid and type `/cofh hand nbt` and it will give you the nbt data for the item you holding, which will have a tag "FluidName" which is what you want to use.

**Comment by gkuba** [comment]
Ah thanks for the info I will give it a shot. I was using the fluid_ender as the fluid name.

**Comment by gkuba** [comment]
That worked perfectly. Also thanks for letting me know about the COFH command I was unaware of that.
