### ISSUE TITLE
Leaves spreading is completely broken on 0.1.6

### ISSUE THREAD

**Issue by JackyyTV** [BloodWorkXGaming/ExNihiloCreatio#58]
I am currently using 0.1.6 of this mod for my pack Lite Island (1.3). It seems like the leaves spreading behavior are broken even when the spreading chance is set to a higher number in config. The leaves are just not spreading at all or takes a very long time to spread. Reverted back to 0.1.5 and everything seems fine.

It seems like you should be using `rand.nextInt(100)` instead of `rand.nextFloat()` in these places:

https://github.com/BloodWorkXGaming/ExNihiloCreatio/blob/f3778ee92441c8946c9f5e8bcd6a76f0afed5c04/src/main/java/exnihilocreatio/blocks/BlockInfestedLeaves.java#L69

https://github.com/BloodWorkXGaming/ExNihiloCreatio/blob/f3778ee92441c8946c9f5e8bcd6a76f0afed5c04/src/main/java/exnihilocreatio/blocks/BlockInfestingLeaves.java#L124

**Comment by BloodWorkXGaming** [comment]
ye, it kinda has some problems with reading the different versions of the config file, but besides that, ye, it is pretty broken anyways, will look into it.

**Comment by JackyyTV** [comment]
Ah okay.

**Comment by GWSheridan** [comment]
Setting the config D:leavesSpreadChance=1 will allow infested leaves to spread its just slow
tested I:leavesSpreadPercent=25 and I:leavesSpreadPercent=60 did not make any difference
An setting I:leavesUpdateFrequency=80 didnt change anything
but changing I:leavesUpdateFrequency=80 to 20 stops the spread
