### ISSUE TITLE
[1.12.2] JEI Sieve visualisation problem

### ISSUE THREAD

**Issue by accessdenied0** [BloodWorkXGaming/ExNihiloCreatio#59]
Minecraft: 1.12.2
Forge: 14.23.1.2594
Ex-Nihilo: 1.12-0.1.7
Other-mods: jei_1.12.2-4.8.5.147

I need to confirm this but, I'm pretty sure the Sieve-mechanics are a bit broken right now.

Sand as well as Soulsand, even if registered, are not listed in JEI and it is not possible to process them.

In addition, I noticed that if you click in JEI on the "Sieve" name to filter for Sieve-recipes in general, all taps [appear to be empty](http://puu.sh/z7g5d/891e8daa7c.png). You have to either search for (click on) [the resource itself or the mesh](http://puu.sh/z7g6d/a33cd249c9.png).

If you need any more details or logs, I post them after request. 

The modpack used here is the High-Tech-a-Sky 2 .

access_deneid

**Comment by BloodWorkXGaming** [comment]
Hey ^^ this really sounds like some kind of error in the json file, like a
missing  `, ` or something which can cause the whole file to not be loaded
correctly.

Wanna send that one for me to look at?

accessdenied0 <notifications@github.com> schrieb am Mo., 22. Jan. 2018,
19:27:

**Comment by accessdenied0** [comment]
Hey @BloodWorkXGaming, 

Yes... i was a bit fast here. You are probably right. I validated the json table and it was indeed an error... do you have a good editor for that?

I'm really sorry for that mistake of mine...

[Here is the invalid JSON.](https://pastebin.com/hQk0ZW1h)

Sadly the second issue with JEI persists.

Line 414: a comma to much.

**Comment by BloodWorkXGaming** [comment]
No worries ^^
I use the one built into intellij, but I don't think it is worth
downloading a whole Java ide just for the json support :P

And regarding the jei thing, I don't really understand it. From the images
it looks like one is the heavy sieve and one is not.
Do the recipes work if you try them in the world and just don't show up in
jei?

accessdenied0 <notifications@github.com> schrieb am Mo., 22. Jan. 2018,
19:32:

**Comment by accessdenied0** [comment]
[Here is the corrected one.](https://pastebin.com/P3Z3wN5e)

The recipes work fine. But JEI seem to bug out.

If you click on a material in JEI, [it is shown.](http://puu.sh/z7gL4/c3f4985eb6.png)

If you click now on "Sieve" like you wanna filter for the recipe, [it is empty.](http://puu.sh/z7g5d/891e8daa7c.png)

If you search for "usage" of the mesh (inside JEI for example) , [it is shown.](http://puu.sh/z7g6d/a33cd249c9.png)

Sorry again, I should have thought on JSON first. You are very friendly.

**Comment by BloodWorkXGaming** [comment]
Okey, just checked it out in my dev envo... maybe there is something broken... but not with jei, rather the whole thing.... for me only coal ist siftable rn....

Will look into it...

**Comment by BloodWorkXGaming** [comment]
okey, fuck me.... I had a script that removed all other stuff and added coal....

**Comment by BloodWorkXGaming** [comment]
But, now that I have fixed that, I can't really replicate your issue... 
No matter whether I click on the sieve or on the item or where ever, can't really get it to not show....

Maybe make a gif or something if I am just not getting the way you mean? ^^

**Comment by accessdenied0** [comment]
Like I mentioned I use the High-Tech-a-Sky 2 mod-pack... (slightly modified)

I can post a log and my mod-list too if needed.

Here is the gif to the issue: http://puu.sh/z7rWj/8cf4fa1626.gif

If you need any other help or things, I try to help.^^

I might to add, that there is no "slot" rendered, too. It appears completely empty.
