### ISSUE TITLE
Ore piece to ore chunks (saw closed so re-opening)

### ISSUE THREAD

**Issue by jmac460** [BloodWorkXGaming/ExNihiloCreatio#60]
So basically my issue is that when i go to craft using the ore pieces, they turn into vanilla minecraft ores, and not the ones supplied by Exnihilo. Also, some of the ore pieces go to Thermal Foundation. 
![image](https://user-images.githubusercontent.com/34420502/36244994-55d546ea-11ee-11e8-8d63-da1fc1d0a8de.png)

![image](https://user-images.githubusercontent.com/34420502/36245011-704ee904-11ee-11e8-85bc-6e5842675346.png)

So this demonstrates the issues. The crafting recipes default to ThermalFoundation, and vanilla.

**Comment by BloodWorkXGaming** [comment]
Uhh, what modpack are you using? And are you using unidict in it?

jmac460 <notifications@github.com> schrieb am Do., 15. Feb. 2018, 08:21:

**Comment by jmac460** [comment]
This is not a modpack. I used just Exnihilo and cofh as well as tinkers construct (all should be compatible with each other) . I removed unidict and it fixed the problems for now, but these issues used to not exist.

**Comment by jmac460** [comment]
Also, not sure if i should open up a new issue, but the Diamond mesh and Iron mesh (i believe) have backwards level 3 and level 4 items. Iron can get way more items than diamond, and diamond has lower chances as well as fewer items you can receive through sieving.

**Comment by BloodWorkXGaming** [comment]
Well, if I remember correctly, the diamond mesh is able to get your more
diamonds and emeralds, the iron mesh gets you more normal ore.

And regarding the unidict issue, I'll look into it... It probably is
because we added a oredict to the ore Chunks.

jmac460 <notifications@github.com> schrieb am Do., 15. Feb. 2018, 22:31:

**Comment by jmac460** [comment]
Okay. Thank you! I opened an issue with unidict as well, since they are having issues with your mod (the compat for them throws errors but not sure why). I let them know of this so they can look into it as well.
