### ISSUE TITLE
[COL] When renaming file

### ISSUE THREAD

**Issue by drakray** [BloodWorkXGaming/ExNihiloCreatio#62]
https://pastebin.com/LViEc2B9
Renaming TinkersComplement-1.12.1-0.2.2b.jar to 2-3-TC-TinkersComplement-1.12.1-0.2.2b.jar causes this mod to load before ExNihilo, and crash.
Reverting name fix this (error in dependency?)

**Comment by BloodWorkXGaming** [comment]
shouldn't happen but, ye, dependency name is wrong here: https://github.com/KnightMiner/TinkersComplement/blob/master/src/main/java/knightminer/tcomplement/TinkersComplement.java#L27
has to be fixed on their side.

**Comment by drakray** [comment]
Sorry, I meant to post that on Tinker's Complement page lol, I got mixed up in my multiple crash reporting for today XD

**Comment by BloodWorkXGaming** [comment]
No worries ^^
