### ISSUE TITLE
[request] Ender IO integration

### ISSUE THREAD

**Issue by HenryLoenwind** [BloodWorkXGaming/ExNihiloCreatio#66]
Hi,

would be nice if you could include a sieve recipe for Ender IO in the defaults.

"oredict:dustBedrock", from dust, diamond mesh, 1%

It's used to craft machine chassis (1x) and capacitors (2x), so fairly low volume required.

Thx.

**Comment by BloodWorkXGaming** [comment]
Added with 86e60cbd4c4bbc3364c6b4c251a00ee0f15c7a6e is there anything else that needs sifting/hammering/composting/whatevering?

**Comment by HenryLoenwind** [comment]
Thanks.

No, that is the only thing in Ender IO that isn't made from normal vanilla items (aside from the broken spawner, and for that one we ship an optional crafting recipe), Operating under a "no worldgen" guideline does have some advantages in that respect... ;)
