### ISSUE TITLE
extrautils2 mechanical user can't sieve even if fakePlayersCanSieve is true

### ISSUE THREAD

**Issue by liquidev** [BloodWorkXGaming/ExNihiloCreatio#67]
I wanted to add simple sieve automation instead of the auto sieves to my modpack, but `fakePlayersCanSieve` doesn't seem to work with it. I have checked the code, there seems to be no problem but it still just doesn't work (user set to Activate Block with Item (Right Click))

**Comment by drmorgmd** [comment]
it works for me. Is your mechanical user set to always on? Also is it facing down directly on the sieve? If you try and manually do it dose it work?

**Comment by liquidev** [comment]
@drmorgmd My mechanical user is set to Always On, I even tried cycling through all the different redstone modes, adding speed upgrades and that didn't help. I have also tried a few different placements of the user, either above the sieve facing down, or next to the sieve facing it, even under the sieve but nothing worked. The sieve is a 4×4 multiblock and I can sieve manually.

**Comment by drmorgmd** [comment]
Ok the only thing i can think of is that you have an issue with your "true" make sure you have no spaces after the = and its all lower case.

**Comment by SirLyle** [comment]
If this issue persists please post your config file and a screenshot of the user's interface.

**Comment by SirLyle** [comment]
If you still have this issue with the latest version please open a new issue with more information (including all mods installed and their versions).

**Comment by liquidev** [comment]
The issue wasn't present when I played Stoneblock. It was probably my fault as dmorgmd suggested, but I don't have the pack anymore so I can't check.
