### ISSUE TITLE
Dupe issue with Smashing

### ISSUE THREAD

**Issue by HenryLoenwind** [BloodWorkXGaming/ExNihiloCreatio#68]
https://github.com/BloodWorkXGaming/ExNihiloCreatio/blob/1.12/src/main/java/exnihilocreatio/compatibility/tconstruct/ModifierSmashing.java#L55

Smashing does not check if the item to be dropped still is in the drop list before putting its own result in. So if it was already moved out of there by another modifier, the block is duped.

Sadly there is no way to specify an execution order for modifiers and traits...

**Comment by BloodWorkXGaming** [comment]
I don't fully understand what you mean, do you mind giving me a modifier combination which causes this to happen?

**Comment by HenryLoenwind** [comment]
Sure. Both of these: https://github.com/SleepyTrousers/EnderIO/tree/master/enderio-integration-tic/src/main/java/crazypants/enderio/integration/tic/traits

(before I blacklisted smashing there)

**Comment by BloodWorkXGaming** [comment]
Ohhhhhhh, I get it now.
However I am not sure how this could be fixed...?
Like I could check whether the list is empty and if it is then don't drop
stuff, but that would prevent blocks which don't drop anything to work.
Or I could check whether the broken block is in the list, but like
Redstone, a block doesn't have to drop itself.

What would he handy is like a droplist altered flag or something....

Any ideas?

Henry Loenwind <notifications@github.com> schrieb am Mi., 14. März 2018,
02:27:

**Comment by BloodWorkXGaming** [comment]
Currently no way good way I can think of to fix this, so the blacklist must be enough...
