### ISSUE TITLE
Add Draconium enhancement 

### ISSUE THREAD

**Issue by drmorgmd** [BloodWorkXGaming/ExNihiloCreatio#70]
Hello, 
Let me start off by saying that i love this mod and the different variations/improvements that keep coming out. I am almost sure that you are working to add draconium ore chunks to Creatio but, i did not see it in the to do list. So are you going to add it and when will the next update be (if you can say) no rushing just wondering. 
Thank you.

**Comment by SirLyle** [comment]
I am unaware of any current plans to add draconium (but you can add it using the json system). Hard to balance such an unbalanced material.

Updates are not scheduled, and tend to be done on a "as it is ready" basis.

**Comment by BloodWorkXGaming** [comment]
Added support with 311bab352eb98c3a731988c46076bc39db76b49d
