### ISSUE TITLE
crash trying to render sieve's

### ISSUE THREAD

**Issue by MasterSloth1** [BloodWorkXGaming/ExNihiloCreatio#71]
forge - 14.23.2.2627
ExNihiloCreatio - 1.12.0.1.7

we teleport back to base and then we crash, reply for any more info u need

https://pastebin.com/k5LxP4cw

**Comment by BloodWorkXGaming** [comment]
Hey ^^
Could you please try this version and check whether it is still happening?
https://ci.blamejared.com/job/ExNihiloCreatio/job/Tencao-registry_changes/38/

**Comment by MasterSloth1** [comment]
sorry for the late reply it seems i cant reproduce this anymore so i haven't been able to test that new build
same world and no mods updated :/ it was only happening on a server. In my single player world it would not crash if that helps at all

**Comment by BloodWorkXGaming** [comment]
Well, ye, that's something that shouldn't happen... A air block apperently
had a sieve tile entity...

MasterSloth1 <notifications@github.com> schrieb am Mo., 19. März 2018,
05:53:

**Comment by MasterSloth1** [comment]
interesting could that be due to a plugin ive been noticing a message pop up in chat saying i dont have permission to interact with minecraft:air i know its not your plugin but im stumped for ideas. i find it very interesting that one day its crashing about 10 ish times to me and my friend then the next day works perfectly fine

**Comment by BloodWorkXGaming** [comment]
This is hopefully fixed, closing for now
