### ISSUE TITLE
[Question] slime

### ISSUE THREAD

**Issue by ChilledDayz** [BloodWorkXGaming/ExNihiloCreatio#72]
How do I get slime? Or is it not implemented yet?

**Comment by SirLyle** [comment]
I don't think it is implemented.

**Comment by ChilledDayz** [comment]
Ah thanks, I've managed to add it using witchwater and a leaf block in a stone barrel. For what I need this works fine.

**Comment by SirLyle** [comment]
I am working on a method of obtaining slime. Glad that you have something that works in the meantime.

**Comment by SirLyle** [comment]
I have added a [branch](https://github.com/BloodWorkXGaming/ExNihiloCreatio/tree/Eww_It's_Slimey) where milk+mushrooms makes a slime block while spawning up to 4 small slimes nearby.

**Comment by ChilledDayz** [comment]
That sounds like an interesting way of doing things.

**Comment by BloodWorkXGaming** [comment]
Added with 598525ed9a4f9b9eac0ec09c45650c9998e16bb9
