### ISSUE TITLE
Enchanting Meshes

### ISSUE THREAD

**Issue by NielsPilgaard** [BloodWorkXGaming/ExNihiloCreatio#73]
Hey! 
I was wondering, is it intentional that you cannot enchant meshes directly in an Enchanting Table or not?

Minecraft 1.12.2
exnihilocreatio-1.12-0.1.7.63

**Comment by SirLyle** [comment]
It looks like it is suppose to be able to apply the enchantments at the table.

**Comment by BloodWorkXGaming** [comment]
Honestly I am not sure anymore, I maybe  did it tentionally because the
enchantment are freaking op and you get them 100% because there are no
other enchantments for meshes.
But it's too long so no idea anymore, might have to revisit it ^^

SirLyle <notifications@github.com> schrieb am Fr., 30. März 2018, 01:37:

**Comment by SirLyle** [comment]
All the enchantments have 

    public boolean canApplyAtEnchantingTable(ItemStack stack) {
        return stack.getItem() instanceof ItemMesh;
    }

so it is trying to allow for them to added in the table.

**Comment by BloodWorkXGaming** [comment]
Alright, will have to check it out after Easter unless you want to? ^^

SirLyle <notifications@github.com> schrieb am Fr., 30. März 2018, 01:50:

**Comment by SirLyle** [comment]
I'm looking at it now, it appears that the canApplyAtEnchantingTable is never being called on the meshes.

**Comment by BloodWorkXGaming** [comment]
Maybe check whether the mapping changed in some of the mcp updates?

SirLyle <notifications@github.com> schrieb am Fr., 30. März 2018, 02:03:

**Comment by SirLyle** [comment]
I found the issue, we just need to override isEnchantable to return true. The enchantability values seem all messed up and prevents anything but efficiency from being selected.

**Comment by SirLyle** [comment]
Never mind about the enchatability...my test setup had no bookshelves.

**Comment by SirLyle** [comment]
Fix merged.

**Comment by NielsPilgaard** [comment]
Thanks!
