### ISSUE TITLE
infested leaf textures flickering with texture pack

### ISSUE THREAD

**Issue by darthvader45** [BloodWorkXGaming/ExNihiloCreatio#75]
I'm currently using the John Smith Technician's Remix pack and noticed the infested leaves are flickering quite a bit.  Any idea why, or is this an animated texture the pack has?

**Comment by BloodWorkXGaming** [comment]
Do you mind posting a gif of the flickering, could be z stuttering or
something else, can't really tell without seeing it myself.

darthvader45 <notifications@github.com> schrieb am Do., 19. Apr. 2018,
03:09:

**Comment by darthvader45** [comment]
Will do when I get home, I'm @ work rn.

**Comment by darthvader45** [comment]
![2018-04-20_09 47 06](https://user-images.githubusercontent.com/2816420/39054516-e0fd7954-447f-11e8-888f-dde96132cbfc.png)
Might be something with the infested leaves and Better Foliage.  Will disable the mod and check.

**Comment by darthvader45** [comment]
Ok, nvm, it is definitely this mod, because I disabled Better Foliage and no change, as well as the resource pack only changing the vanilla leaf textures, which this mod relies on.

**Comment by BloodWorkXGaming** [comment]
By this mod you mean ex creatio?
Can you give me a link to the texture pack so I can attempt to fix it?

**Comment by darthvader45** [comment]
Yeah, and the pack's on this site: https://github.com/John-Smith-Modded/JSTR-Modded-1.12.x/releases  1.1.5

**Comment by darthvader45** [comment]
Anything lately?

**Comment by BloodWorkXGaming** [comment]
Well, I tested it with the texture pack you are suggesting but I don't see any flickering so not too sure how much is on my end?

**Comment by darthvader45** [comment]
Huh, I'll test with just this mod and the resource pack.  Idk how any other mod could be messing with the tree leaves aside from Serene Seasons being added recently (and I had the flickering before that).  Could be Dynamic Surroundings.  I'll get a screenshot of my mods.

**Comment by darthvader45** [comment]
![mod list dragons](https://user-images.githubusercontent.com/2816420/45934774-ca88b780-bf70-11e8-9d07-df3f16ba0463.PNG)
Here's my modlist.  What could be messing with the textures?  Can't be Serene Seasons, that was a recent addition and I've had the flickering well before that mod was added.

**Comment by BloodWorkXGaming** [comment]
Could also be optifine, and can you please post a _gif_ of it not a png?

darthvader45 <notifications@github.com> schrieb am Mo., 24. Sep. 2018,
02:40:

**Comment by darthvader45** [comment]
Sure, will do.  Will also test with and w/o Optifine to determine if it is the problem.  If so, might just have to deal with it, as Optifine compat is just about impossible.

**Comment by darthvader45** [comment]
Here's the gif, also got this w/o Optifine:

![ezgif com-optimize](https://user-images.githubusercontent.com/2816420/45965516-a8397d00-bff6-11e8-912f-fcf248c24920.gif)

**Comment by SirLyle** [comment]
Can you confirm if you still have this issue with the latest version of Ex Nihilo?

**Comment by darthvader45** [comment]
Will check, not sure.

**Comment by darthvader45** [comment]
Have latest version of Ex Nihilo Creatio and Optifine, as well as BetterFPS and Foamfix.  Can confirm flickering is indeed gone.  Thanks so much.  What was the cause?  I was guessing maybe z-fighting in the infested leaves texture?

**Comment by SirLyle** [comment]
No clue, it probably got fixed during general code clean up, or it was due to another mod which got fixed. I was never able to reproduce it.
