### ISSUE TITLE
[1.12.2] Broken Crucible Render In JEI

### ISSUE THREAD

**Issue by TheLimePixel** [BloodWorkXGaming/ExNihiloCreatio#77]
In the latest version, the Crucible render in JEI broke.
![image](https://user-images.githubusercontent.com/25333164/39042900-57b5921e-448c-11e8-96ea-458c0c0ec259.png)

**Comment by BloodWorkXGaming** [comment]
![image](https://user-images.githubusercontent.com/8137062/39043384-8f121826-448d-11e8-953d-ecc5e1f50b84.png)
Works for me, do you have optifine installed?

**Comment by TheLimePixel** [comment]
Nope.

**Comment by TheLimePixel** [comment]
Hmmm, now when I loaded up the game it's fine.... weird.

**Comment by BloodWorkXGaming** [comment]
Alrighty, if it reoccurs just reopen the issue, but might be just a temporary opengl wierdness ^^
