### ISSUE TITLE
[Suggestion] Default Thermal Foundation support

### ISSUE THREAD

**Issue by TheLimePixel** [BloodWorkXGaming/ExNihiloCreatio#78]
Previous versions of Ex Nihilo had default Thermal Foundation support, but this one does not. This simply includes Platinum Ore Chunks and Pyrotheum being a heat source for the Crucible. I know I can manually add it, but why wouldn't it be a default?

**Comment by BloodWorkXGaming** [comment]
Good question, mostly because I forgot, do you have any suggested numbers for the drop rarity?

**Comment by BloodWorkXGaming** [comment]
Added a bit of support with 9cc97fd91666b8f889dbebbbe19f023406b25547 need to create a new registry for improved mob spawn handling tho for the blizzes and so on

**Comment by TheLimePixel** [comment]
Hmmm, are you saying that you are going to have Blizz, Blitz and Basalz Dolls? :D

**Comment by BloodWorkXGaming** [comment]
Not sure whether dolls or just click a molten Redstone barrel with like a
blaze rod or something.

EmosewaPixel <notifications@github.com> schrieb am Sa., 21. Apr. 2018,
01:06:

**Comment by TheLimePixel** [comment]
The question is what would you have the barrel filled with? Blitzes are associated with Niter. Blizzes with Snowballs and Basalzes with Pulverized Obsidian, none of which have a fluid variant.

**Comment by BloodWorkXGaming** [comment]
well, maybe all redstone and associate different items for the different mobs?
Or maybe I need a doll registry, but that wouldn't work well with textures....

**Comment by TheLimePixel** [comment]
How wouldn't it work well? Since they are all like blazes, the textures would just be the blaze doll's with a changed color.

**Comment by BloodWorkXGaming** [comment]
Well ye ofc, I could add just copies of the normal doll for those ones, but
having a registry for any doll for any various mob doesn't work very well I
could imagine...
Also I like my dolls to have little bit of personality, like the shulker
doll splitting in the middle like the shulker is doing :P

EmosewaPixel <notifications@github.com> schrieb am Sa., 21. Apr. 2018,
01:23:

**Comment by TheLimePixel** [comment]
But, maybe you shouldn't even have them spawnable. You can make their dusts with the Fluid Transposer anyways.

**Comment by BloodWorkXGaming** [comment]
Don't you need the rods they drop for some stuff?

EmosewaPixel <notifications@github.com> schrieb am Sa., 21. Apr. 2018,
01:29:

**Comment by TheLimePixel** [comment]
Nope.

**Comment by BloodWorkXGaming** [comment]
Ah that's cool, will consider it then, but would still be a cool feature to
have ^^

EmosewaPixel <notifications@github.com> schrieb am Sa., 21. Apr. 2018,
01:33:

**Comment by TheLimePixel** [comment]
Well, since you implemented what I initially asked for, I'm going to close this.

**Comment by TheLimePixel** [comment]
Btw, 6adaff is a much better color value for platinum.

**Comment by BloodWorkXGaming** [comment]
Well, depends on whether we want to be scientific accurate or rather match
the color from thermal....

EmosewaPixel <notifications@github.com> schrieb am Sa., 21. Apr. 2018,
22:04:

**Comment by TheLimePixel** [comment]
I'd rather go with the latter. It and Tech Reborn are pretty much all the mods that add Platinum anyways.
