### ISSUE TITLE
Lava in stone barrel + item is making netherrack every time

### ISSUE THREAD

**Issue by marckskl** [BloodWorkXGaming/ExNihiloCreatio#79]
Looks like with freshly generated configs Lava & Glowstone, Lava & Sky Stone Dust are creating Netherrack instead of End Stone & Sky Stone blocks respectively. Any chance for a quick fix? 
EDIT: It's happening on version 0.2.0.

**Comment by BloodWorkXGaming** [comment]
Can you please try this version?
https://ci.blamejared.com/job/ExNihiloCreatio/job/1.12/4/
I hope I fixed it in that (also oredict support for barrels now)

**Comment by marckskl** [comment]
That works. End stone and sky stone are craftable via barrels again :)

**Comment by BloodWorkXGaming** [comment]
Awesome! gonna release to curse soon then!
