### ISSUE TITLE
game crash on start after crafting hammer

### ISSUE THREAD

**Issue by Kenshij** [BloodWorkXGaming/ExNihiloCreatio#82]
Modpack Enigmatica 2 Expert v1.20

java.lang.NoSuchMethodError: exnihilocreatio.registries.registries.HammerRegistry.registered(Lnet/minecraft/block/Block;)Z

https://pastebin.com/5xfvjM8F

**Comment by BloodWorkXGaming** [comment]
Try updating your creation, I think I already released a hotfix for that...

Kenshij <notifications@github.com> schrieb am Sa., 28. Apr. 2018, 12:50:

**Comment by BloodWorkXGaming** [comment]
*creatio

BloodWorkXGaming <bloodworkxgaming@gmail.com> schrieb am Sa., 28. Apr.
2018, 21:12:

**Comment by Kenshij** [comment]
ah ok thanks ^^ will handy update the mod

**Comment by Kenshij** [comment]
modepack uses latest version exnihilocreatio-1.12-0.2.1.jar, so in this version is no fix for the crash

have delted the hammer from inventory trough ntbeditor, to continue playing  

crash appears when you have the hammer in active slot and something (think it is waila harvestability) checks if you can break the block with the tool, have looked at a the tinker workbench, so yes your mod couse in the end the crash but don't know if not waila should fix this

**Comment by BloodWorkXGaming** [comment]
ah, shit sorry, then I fixed it and forgot to release it to curse...
You can use a version from here till I upload it
https://ci.blamejared.com/job/ExNihiloCreatio/job/1.12/

Kenshij <notifications@github.com> schrieb am Sa., 28. Apr. 2018, 23:57:

**Comment by NielsPilgaard** [comment]
That version does indeed fix it, thank you!

**Comment by Kenshij** [comment]
Thanks for the linkt from me, too :D
