### ISSUE TITLE
Tinkers Sledge Hammer crash with ExNihiloCreatio [1.12.2]

### ISSUE THREAD

**Issue by Fundryi** [BloodWorkXGaming/ExNihiloCreatio#84]
Forge: 1.12.2 - 14.23.3.2677
Singleplayer/Client crash
When making/using a tinkers sledgehammer I immediately crash and can not re-enter the world.
idk looks like a cross mod problem.

Crashlog: https://pastebin.com/raw/N8XzQ4K7
Another crash: https://github.com/Fundryi/Destiny/issues/9

Regards, Fundryi

**Comment by BloodWorkXGaming** [comment]
https://ci.blamejared.com/job/ExNihiloCreatio/job/1.12/
use a version from here till i get around to release it

**Comment by Fundryi** [comment]
I can confirm that version fixed it, thank you!

**Comment by Fundryi** [comment]
Can u update your mod today? I don't wanna stress you at all. Its just I can publish my Modpack updated without u uploading it to Official Curse.

Regards, Fundryi

**Comment by BloodWorkXGaming** [comment]
https://minecraft.curseforge.com/projects/ex-nihilo-creatio/files/2557430

For when it is approved ^^

**Comment by Fundryi** [comment]
Thank u so much!

**Comment by BloodWorkXGaming** [comment]
Damn, they approved it quite quickly :D
