### ISSUE TITLE
Crucible heat sources Manyullyn and Uranium do not work

### ISSUE THREAD

**Issue by SierraGhost** [BloodWorkXGaming/ExNihiloCreatio#87]
Issue: Using a manyullyn block, or uranium block below a crucible provides a zero times multiplier.
Expected behaviour: Multiplier meets what is listed in JEI interface. 6x and 8x respectively, iirc.

Versions Tested: exnihilocreatio-1.12-0.2.2 with TConstruct-1.12.2-2.10.0.75 for Manyullyn block

**Comment by SirLyle** [comment]
Could you please upload your <minecraft>/config/exnihilocreatio/HeatRegistry.json file to pastebin and post a link?

Do you have any other mods installed?

**Comment by SierraGhost** [comment]
Edit: I realise this doesn't show off the IC2: Uranium issue, but it's much the same. I just found it easier to test with Manyullyn

Found this in the latest release of Forever Stranded: Losts Souls Modpack.

However this was confirmed by creating a new profile and loading the mods listed below. The last three aren't necessary, but they list the heat source in JEI as x6 for Manyullyn, and The One Probe shows multiplier as x0. Loading the crucible with cobblestone also does not generate lava.

- TConstruct-1.12.2-2.10.0.75
- Mantle-1.12-1.3.2.24
- exnihilocreatio-1.12-0.2.2
- jei_1.12.2-4.9.1.175
- JustEnoughResources-1.12.2-0.8.7.41
- theoneprobe-1.12-1.4.22

HeatRegistry Attached: https://pastebin.com/hzAGs4KL
![2018-05-22_12 19 45](https://user-images.githubusercontent.com/30785466/40338798-9912f048-5dba-11e8-93b7-2e8d0474f204.png)

**Comment by SirLyle** [comment]
Thank you for reporting, I am able to duplicate it:

From the log using the minimal setup described above:

    [18:32:15] [INFO] JEI: Heat Sources Loaded:             7

So it is loading the recipes.

Appears to be caused by: [TileCrucibleStone.java:96](https://github.com/BloodWorkXGaming/ExNihiloCreatio/blob/ab8cd864e9cfc476c080125c70a771a2cfaf7e58/src/main/java/exnihilocreatio/tiles/TileCrucibleStone.java#L96) ignoring metadata:

     int heat = ExNihiloRegistryManager.HEAT_REGISTRY.getHeatAmount(new BlockInfo(stateBelow.getBlock()));

I have uploaded a fix

**Comment by SierraGhost** [comment]
Thanks for the update @SirLyle, much appreciate it!
