### ISSUE TITLE
[Suggestion] Plans to add AE2/Extreme Reactors compat?

### ISSUE THREAD

**Issue by Rocky28447** [BloodWorkXGaming/ExNihiloCreatio#9]
In original Ex Nihilo, Lava + AE2 Sky Stone Dust in a barrel yielded Sky Stone, and Yellorium dust from Big Reactors could be obtained by sifting sand, as there are no other ways to obtain them in Skyblock modpacks.

Not sure if you had plans to re-add this and haven't gotten around to it yet or just forgot about it.

**Comment by BloodWorkXGaming** [comment]
Well, nothing is stopping you from putting it in your own configs and
making it therefore obtainable.

**Comment by SirLyle** [comment]
Added some cross mod support and set up the code to easily add more.
