### ISSUE TITLE
Meshes have durability, or can be combined (including enchantments)

### ISSUE THREAD

**Issue by darthvader45** [BloodWorkXGaming/ExNihiloCreatio#91]
I understand that sieve meshes can be enchanted and such, but the problem is the only way to get powerful enchantments on them is to have max bookshelves.  Could there be an added ability to combine enchanted meshes on an anvil to improve enchantments?  I had to use JEI to artificially do this, and it would please me greatly to combine meshes to boost enchantment power.  I was trying to combine 2 sieve efficiency II sieve fortune I diamond stiffened meshes.

**Comment by SirLyle** [comment]
I don't think it is feasible to add mesh durability since currently the metadata is used to differentiate mesh types (would be better to not use that, so we could have many types of meshes). But I have anvil combining of the enchantments working on a branch.

**Comment by SirLyle** [comment]
Durability is infeasible to add with the current system, I have merged some fixes for enchanting/anvil use.

**Comment by darthvader45** [comment]
Thank you, this will help greatly.
