### ISSUE TITLE
Crash on Load, Potentially with the Dolls

### ISSUE THREAD

**Issue by FallenEagle1** [BloodWorkXGaming/ExNihiloCreatio#93]
Had Cheeyev#2468 come in the atm discord channel with this crash. Looking through the logs, it almost looks like forge is seeing all 8 potential dolls, when only a few of them are loaded.

Minecraft: 1.12.2
Forge: 14.23.4.2705
Ex Nihilo Creatio: 1.12-0.2.3

Crash Logs:
https://pastebin.com/AcGr2KJ0 --- Looks like this one is set to expire on 6/26
http://openeye.openmods.info/crashes/59490234b51180af22977b2ebe6e45be

**Comment by FallenEagle1** [comment]
Looking a little in ItemDoll.java, is there a spot where the mod looks at the max number of enum's, since there are 8 at all times even if the other mods are not present?

**Comment by BloodWorkXGaming** [comment]
Should be fixed now, for anyone wondering, was happening when tinkers is installed, but thermals is not ^^
