### ISSUE TITLE
[Suggestion] Config file for adding liquids and blocks as crucible heating blocks.

### ISSUE THREAD

**Issue by noamsm** [BloodWorkXGaming/ExNihiloCreatio#95]
Add a config file that allows the user to add blocks that could heat up the crucible,
Example:
`{
    "minecraft:torch": 1,
    "liquid:lava": 3
}`

**Comment by SirLyle** [comment]
That exists in the HeatRegistry.json file. You need to enable json files in the configs, run the game once, then you can edit `<minecrat>/config/exnihilocreatio/HeatRegistry.json`.
