### ISSUE TITLE
Top Issue On Servers

### ISSUE THREAD

**Issue by TheLimePixel** [BloodWorkXGaming/ExNihiloCreatio#96]
When looking at Sieves on servers, instead of the Mesh being used being displayed, you get an error.
![image](https://user-images.githubusercontent.com/25333164/41968253-21279a0a-7a04-11e8-9181-b0133d04fa38.png)

**Comment by BloodWorkXGaming** [comment]
There should be a oneProbe log somewhere I think, could you maybe send me
that please? ^^

EmosewaPixel <notifications@github.com> schrieb am Mi., 27. Juni 2018,
12:18:

**Comment by TheLimePixel** [comment]
It doesn't seem to have its own log
